modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="oneiricconcept"
version="1.9.67"
displayName="\u68A6\u534E\u6784\u60F3OneiricConcept"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="GlowStar, Pepper\u67D0\u4EBA\uFF0CMCreator"
description="\u539F\u77F3\u5DE5\u827A\u7684\u9644\u5C5E\u6A21\u7EC4"

# Start of user code block mod configuration
[[mixins]]
config = "oneiricconcept.mixins.json"
# End of user code block mod configuration

[[dependencies.oneiricconcept]]
modId="neoforge"
type="required"
versionRange="[21.1.92,)"
ordering="AFTER"
side="BOTH"

[[dependencies.oneiricconcept]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"

[[dependencies.oneiricconcept]]
modId="primogemcraft"
type="required"
versionRange="[0,)"
ordering="NONE"
side="BOTH"



# Start of user code block dependencies configuration
[[dependencies.oneiricconcept]]
modId="genshincraft"
type="optional"
versionRange="[2.5.0,)"
ordering="AFTER"
side="BOTH"
# End of user code block dependencies configuration
