/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.oneiricconcept.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.fluids.capability.wrappers.FluidBucketWrapper;
import net.neoforged.neoforge.common.DeferredSpawnEggItem;
import net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.OnlyIn;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.client.renderer.item.ItemProperties;

import net.mcreator.oneiricconcept.procedures.VastmodeProcedure;
import net.mcreator.oneiricconcept.procedures.TexturesProcedure;
import net.mcreator.oneiricconcept.procedures.BowPullProcedure;
import net.mcreator.oneiricconcept.item.*;
import net.mcreator.oneiricconcept.OneiricconceptMod;

public class OneiricconceptModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(OneiricconceptMod.MODID);
	public static final DeferredItem<Item> SAUSAGE;
	public static final DeferredItem<Item> SMOKE_SAUSAGE;
	public static final DeferredItem<Item> BELOBOG_SAUSAGE;
	public static final DeferredItem<Item> S_2AUSAGE;
	public static final DeferredItem<Item> S_2MOKE_SAUSAGE;
	public static final DeferredItem<Item> B_2ELOBOG_SAUSAGE;
	public static final DeferredItem<Item> STUFFING;
	public static final DeferredItem<Item> S_2TUFFING;
	public static final DeferredItem<Item> GEOMARROW_RADIATOR;
	public static final DeferredItem<Item> ONEIRIC_SHARD;
	public static final DeferredItem<Item> MORA_SAUSAGE;
	public static final DeferredItem<Item> PRIMOGEMS_SAUSAGE;
	public static final DeferredItem<Item> BOOM_BLOSSOMS_PYRO;
	public static final DeferredItem<Item> BANANA_MUSHROOM;
	public static final DeferredItem<Item> BANANA_MUSHROOM_BOCK;
	public static final DeferredItem<Item> ELEMENTS_CRYSTAL_ORE;
	public static final DeferredItem<Item> NAGADUS_EMERALD_ORE;
	public static final DeferredItem<Item> SHIVADA_JADE_ORE;
	public static final DeferredItem<Item> VAJRADA_AMETHYST_ORE;
	public static final DeferredItem<Item> VARUNADA_LAZURITE_ORE;
	public static final DeferredItem<Item> CLOUD;
	public static final DeferredItem<Item> PRITHIVA_TOPAZ_ORE;
	public static final DeferredItem<Item> VAYUDA_TURQUOISE_ORE;
	public static final DeferredItem<Item> AGNIDUS_AGATE_ORE;
	public static final DeferredItem<Item> CLOUD_BOTTLE;
	public static final DeferredItem<Item> DREAMDIVE_CAN;
	public static final DeferredItem<Item> SUN_START_CAN;
	public static final DeferredItem<Item> MEMORIA_BUCKET;
	public static final DeferredItem<Item> MEMORY_BUBBLE;
	public static final DeferredItem<Item> MEMORIA_PIECE;
	public static final DeferredItem<Item> XUANYUAN_SWORD;
	public static final DeferredItem<Item> ADEPTUS_GUN;
	public static final DeferredItem<Item> BIG_STONE;
	public static final DeferredItem<Item> BIG_ROCK;
	public static final DeferredItem<Item> HONKAI_SHARD;
	public static final DeferredItem<Item> LEGION_PSEUDO_CORE;
	public static final DeferredItem<Item> LEGION_PSEUDO_SLIVER;
	public static final DeferredItem<Item> HONKAI_SLIVER;
	public static final DeferredItem<Item> OY_DUMPLING;
	public static final DeferredItem<Item> DUMPLING;
	public static final DeferredItem<Item> OY_STUFFING;
	public static final DeferredItem<Item> THE_ANOTHER_WORLD_LOG;
	public static final DeferredItem<Item> STRIPPED_THE_ANOTHER_WORLD_LOG;
	public static final DeferredItem<Item> THE_ANOTHER_WORLD_SAPLING;
	public static final DeferredItem<Item> DARK_XUANYUAN_SWORD;
	public static final DeferredItem<Item> THE_ANOTHER_WORLD_WOOD;
	public static final DeferredItem<Item> CONDENSED_MEMORIA_PIECE;
	public static final DeferredItem<Item> TAW_WOOD_BOX;
	public static final DeferredItem<Item> TAW_WOOD_LOOT;
	public static final DeferredItem<Item> MEMORIA_LOOT;
	public static final DeferredItem<Item> MM_MUSHROOM;
	public static final DeferredItem<Item> MMMHIT;
	public static final DeferredItem<Item> BACTUS;
	public static final DeferredItem<Item> C_CACTUS;
	public static final DeferredItem<Item> GACTUS;
	public static final DeferredItem<Item> MACTUS;
	public static final DeferredItem<Item> RACTUS;
	public static final DeferredItem<Item> YACTUS;
	public static final DeferredItem<Item> SWORD_OF_BRILLIANT_VALOR;
	public static final DeferredItem<Item> THE_ANOTHER_WORLD_LEAVE;
	public static final DeferredItem<Item> CRYSTAL_TURTLE_SPAWN_EGG;
	public static final DeferredItem<Item> TNT_DISPENSER;
	public static final DeferredItem<Item> WAFFLE;
	public static final DeferredItem<Item> PRIMOGEM_WAFFLE;
	public static final DeferredItem<Item> D_XUANYUAN;
	public static final DeferredItem<Item> SMALL_HERTA_CORE;
	public static final DeferredItem<Item> SKY_WAFFLE;
	public static final DeferredItem<Item> RESURRECTION_PELLET;
	public static final DeferredItem<Item> SURPRISEBOXFORGOODORBAD;
	public static final DeferredItem<Item> EXAMPLE;
	public static final DeferredItem<Item> TOTEMLOOT;
	public static final DeferredItem<Item> COMPRESS_TOTEMLOOT;
	public static final DeferredItem<Item> BOSS_STONE_COIN_GUN;
	public static final DeferredItem<Item> MORA_MAGAZINE;
	public static final DeferredItem<Item> MORA_MAGAZINE_E_1;
	public static final DeferredItem<Item> BOSS_STONE_COIN_GUN_PLUS;
	public static final DeferredItem<Item> PUBLIC_CLAMOR;
	public static final DeferredItem<Item> PROPAGANDA_ARMY;
	public static final DeferredItem<Item> PROPAGANDA_ARMY_BLOCK;
	public static final DeferredItem<Item> A_PROPAGANDA_ARMY;
	public static final DeferredItem<Item> THUNDER_SWORD;
	public static final DeferredItem<Item> PGC_PRESENT;
	public static final DeferredItem<Item> PRIMOGEM;
	public static final DeferredItem<Item> PYRO_METAL;
	public static final DeferredItem<Item> CAMERA;
	public static final DeferredItem<Item> SUSTENANCEANCHORITEM;
	public static final DeferredItem<Item> SUSTENANCEANCHOROFF;
	public static final DeferredItem<Item> SUSTENANCEANCHOR;
	public static final DeferredItem<Item> CRESCENT_METAL;
	public static final DeferredItem<Item> REDMOON_METAL;
	public static final DeferredItem<Item> FULLMOON_METAL;
	public static final DeferredItem<Item> TRASHMETAL;
	public static final DeferredItem<Item> ELECTRO_METAL;
	public static final DeferredItem<Item> HYDRO_METAL;
	public static final DeferredItem<Item> CRYO_METAL;
	public static final DeferredItem<Item> DENDRO_METAL;
	public static final DeferredItem<Item> ANEMO_METAL;
	public static final DeferredItem<Item> GEO_METAL;
	public static final DeferredItem<Item> SUPERIMPOSER_CUSTOMMADE;
	public static final DeferredItem<Item> HERTABOND;
	public static final DeferredItem<Item> PYROSEALINGWAX;
	public static final DeferredItem<Item> ELECTROSEALINGWAX;
	public static final DeferredItem<Item> HYDROSEALINGWAX;
	public static final DeferredItem<Item> CRYOSEALINGWAX;
	public static final DeferredItem<Item> DENDROSEALINGWAX;
	public static final DeferredItem<Item> ANEMO_SEALINGWAX;
	public static final DeferredItem<Item> GEOSEALINGWAX;
	public static final DeferredItem<Item> AMBROSIAL_ARBOR_LOG;
	public static final DeferredItem<Item> AMBROSIAL_ARBOR_LEAVE;
	public static final DeferredItem<Item> IGNIS_AURELIAE;
	public static final DeferredItem<Item> AURELIAE_PICKAXE;
	public static final DeferredItem<Item> AURELIAE_AXE;
	public static final DeferredItem<Item> AURELIAE_SWORD;
	public static final DeferredItem<Item> AURELIAE_SHOVEL;
	public static final DeferredItem<Item> AURELIAE_HOE;
	public static final DeferredItem<Item> MOLTEN_METAL;
	public static final DeferredItem<Item> MOLTEN_METAL_BLOCK;
	public static final DeferredItem<Item> PRIMOGEMFRUITBLOCK;
	public static final DeferredItem<Item> PRIMOGEMFRUIT;
	public static final DeferredItem<Item> AMBROSIAL_ARBOR_SAPLING;
	public static final DeferredItem<Item> AMBROSIAL_ARBOR_PLANK;
	public static final DeferredItem<Item> HILTWOOD_FROM_THE_ARBOR;
	public static final DeferredItem<Item> WAYFAREBLESSING;
	public static final DeferredItem<Item> HEARTOFTHEFROZENSEA;
	public static final DeferredItem<Item> HEARTOFTHESKYSEA;
	public static final DeferredItem<Item> HEARTOFTHEWARMSEA;
	public static final DeferredItem<Item> HEARTOFTHEVASTSEA;
	public static final DeferredItem<Item> FLOATING_CLOUD;
	public static final DeferredItem<Item> SALT;
	public static final DeferredItem<Item> MILK;
	public static final DeferredItem<Item> RED_BEAN_SOUP_FILLING_YUAN_XIAO;
	public static final DeferredItem<Item> SWEET_SESAME_FILLING_YUAN_XIAO;
	public static final DeferredItem<Item> GRILLED_OY_DUMPLING;
	public static final DeferredItem<Item> GRILLED_DUMPLING;
	public static final DeferredItem<Item> SALT_DUST;
	public static final DeferredItem<Item> HUNGER;
	public static final DeferredItem<Item> AMBROSIAL_ARBOR_WOOD;
	public static final DeferredItem<Item> AMBERGRIS_CHEESE_SLIVER;
	public static final DeferredItem<Item> DIVINE_ARROW_EMBERS;
	public static final DeferredItem<Item> DEEP_MARROW_ROCK_SALT;
	public static final DeferredItem<Item> FRESH_SEEDOF_DAWN;
	public static final DeferredItem<Item> DAWNLEAVES;
	public static final DeferredItem<Item> XIAO_LANTERN_RECYCLER;
	public static final DeferredItem<Item> HEARTOFTHEFISH;
	public static final DeferredItem<Item> PHLOGISTONTANK;
	public static final DeferredItem<Item> PHLOGISTON_CRYSTAL;
	public static final DeferredItem<Item> PHLOGISTON;
	public static final DeferredItem<Item> FISHCAKE;
	public static final DeferredItem<Item> WAYFARE_CAKE_SLICES;
	public static final DeferredItem<Item> PRIMOGEMCRAFTWIKI;
	public static final DeferredItem<Item> WILDERNESS_ROD;
	public static final DeferredItem<Item> CAMERAPINK;
	public static final DeferredItem<Item> SWEETFLOWER;
	public static final DeferredItem<Item> ICE_FRESH_RAW_FROSTWEAVE_SALMON_SLICES;
	public static final DeferredItem<Item> XUANYUAN_ARROW;
	public static final DeferredItem<Item> FRUITPASTEBAIT;
	public static final DeferredItem<Item> SWEETFLOWERMEDAKA;
	public static final DeferredItem<Item> FISH;
	public static final DeferredItem<Item> MEDAKA;
	public static final DeferredItem<Item> GLAZEMEDAKA;
	public static final DeferredItem<Item> AIZENMEDAKA;
	public static final DeferredItem<Item> VIRTUAL_PARTICLE;
	public static final DeferredItem<Item> SOLID_WATER;
	public static final DeferredItem<Item> CAMO_PAINT;
	public static final DeferredItem<Item> ENERGY_DRINK;
	public static final DeferredItem<Item> ENERGY_DRINK_PRIMOGEM;
	public static final DeferredItem<Item> ENERGY_DRINK_SUGAR_FREE;
	public static final DeferredItem<Item> TREE_BARKOF_ERUDITION;
	public static final DeferredItem<Item> PUNITIVE_ENERGY;
	public static final DeferredItem<Item> MORA_BOW;
	public static final DeferredItem<Item> THIEF_S_INSTINCT;
	public static final DeferredItem<Item> USURPER_S_SCHEME;
	public static final DeferredItem<Item> CONQUEROR_S_WILL;
	public static final DeferredItem<Item> ADEPTUSTOOL;
	public static final DeferredItem<Item> RAINBOW_CACTUS_BALL;
	public static final DeferredItem<Item> SKIP_TOOL;
	public static final DeferredItem<Item> DREAMY_CONE;
	public static final DeferredItem<Item> EXHAUSTEDPRIMOGEM;
	public static final DeferredItem<Item> PRIMOGEMSTORMGLASS;
	public static final DeferredItem<Item> STARDUST_BASEBALLER;
	public static final DeferredItem<Item> CRYSTALGENERATOR;
	public static final DeferredItem<Item> CULLINAN;
	public static final DeferredItem<Item> NEST;
	public static final DeferredItem<Item> ENGINEERINGANTIMATTERBOMBBLOCK;
	public static final DeferredItem<Item> CRESCENTMOONORE;
	public static final DeferredItem<Item> REDMOONORE;
	public static final DeferredItem<Item> FULLMOONORE;
	public static final DeferredItem<Item> RAWCRESCENTMOONORE;
	public static final DeferredItem<Item> RAWREDMOONORE;
	public static final DeferredItem<Item> RAWFULLMOONORE;
	public static final DeferredItem<Item> THEANOTHERWORLDMOONINGOT;
	public static final DeferredItem<Item> WHITE_MOONLIGHT_ABSORBER;
	public static final DeferredItem<Item> FINE_TEA_FULL_MOON;
	public static final DeferredItem<Item> CHENYU_ADEPTEA;
	public static final DeferredItem<Item> CHENYU_ADEPTEA_TREE;
	public static final DeferredItem<Item> CHENYU_ADEPTEA_SEEDLING;
	public static final DeferredItem<Item> THE_BOON_OF_THE_ELDER_TREE;
	public static final DeferredItem<Item> PYRO_BOOMYAM;
	public static final DeferredItem<Item> CELEBRATORY_XIAO_LANTERN;
	public static final DeferredItem<Item> DENDRO_LAUNCH;
	public static final DeferredItem<Item> BOOM_BLOSSOMS_CRYO;
	public static final DeferredItem<Item> BOOM_BLOSSOMS_DENDRO;
	public static final DeferredItem<Item> BOOM_BLOSSOMS_ELECTRO;
	public static final DeferredItem<Item> BOOM_BLOSSOMS_HYDRO;
	public static final DeferredItem<Item> CRYO_BOOMYAM;
	public static final DeferredItem<Item> DENDRO_BOOMYAM;
	public static final DeferredItem<Item> ELECTRO_BOOMYAM;
	public static final DeferredItem<Item> HYDRO_BOOMYAM;
	public static final DeferredItem<Item> TOASTPIZZA;
	public static final DeferredItem<Item> TOAST_TOAST_PIZZA;
	static {
		SAUSAGE = REGISTRY.register("sausage", SausageItem::new);
		SMOKE_SAUSAGE = REGISTRY.register("smoke_sausage", SmokeSausageItem::new);
		BELOBOG_SAUSAGE = REGISTRY.register("belobog_sausage", BelobogSausageItem::new);
		S_2AUSAGE = REGISTRY.register("s_2ausage", S2ausageItem::new);
		S_2MOKE_SAUSAGE = REGISTRY.register("s_2moke_sausage", S2mokeSausageItem::new);
		B_2ELOBOG_SAUSAGE = REGISTRY.register("b_2elobog_sausage", B2elobogSausageItem::new);
		STUFFING = REGISTRY.register("stuffing", StuffingItem::new);
		S_2TUFFING = REGISTRY.register("s_2tuffing", S2tuffingItem::new);
		GEOMARROW_RADIATOR = block(OneiricconceptModBlocks.GEOMARROW_RADIATOR);
		ONEIRIC_SHARD = REGISTRY.register("oneiric_shard", OneiricShardItem::new);
		MORA_SAUSAGE = REGISTRY.register("mora_sausage", MoraSausageItem::new);
		PRIMOGEMS_SAUSAGE = REGISTRY.register("primogems_sausage", PrimogemsSausageItem::new);
		BOOM_BLOSSOMS_PYRO = block(OneiricconceptModBlocks.BOOM_BLOSSOMS_PYRO);
		BANANA_MUSHROOM = block(OneiricconceptModBlocks.BANANA_MUSHROOM);
		BANANA_MUSHROOM_BOCK = block(OneiricconceptModBlocks.BANANA_MUSHROOM_BOCK);
		ELEMENTS_CRYSTAL_ORE = block(OneiricconceptModBlocks.ELEMENTS_CRYSTAL_ORE);
		NAGADUS_EMERALD_ORE = block(OneiricconceptModBlocks.NAGADUS_EMERALD_ORE);
		SHIVADA_JADE_ORE = block(OneiricconceptModBlocks.SHIVADA_JADE_ORE);
		VAJRADA_AMETHYST_ORE = block(OneiricconceptModBlocks.VAJRADA_AMETHYST_ORE);
		VARUNADA_LAZURITE_ORE = block(OneiricconceptModBlocks.VARUNADA_LAZURITE_ORE);
		CLOUD = block(OneiricconceptModBlocks.CLOUD);
		PRITHIVA_TOPAZ_ORE = block(OneiricconceptModBlocks.PRITHIVA_TOPAZ_ORE);
		VAYUDA_TURQUOISE_ORE = block(OneiricconceptModBlocks.VAYUDA_TURQUOISE_ORE);
		AGNIDUS_AGATE_ORE = block(OneiricconceptModBlocks.AGNIDUS_AGATE_ORE);
		CLOUD_BOTTLE = REGISTRY.register("cloud_bottle", CloudBottleItem::new);
		DREAMDIVE_CAN = REGISTRY.register("dreamdive_can", DreamdiveCanItem::new);
		SUN_START_CAN = REGISTRY.register("sun_start_can", SunStartCanItem::new);
		MEMORIA_BUCKET = REGISTRY.register("memoria_bucket", MemoriaItem::new);
		MEMORY_BUBBLE = REGISTRY.register("memory_bubble", MemoryBubbleItem::new);
		MEMORIA_PIECE = REGISTRY.register("memoria_piece", MemoriaPieceItem::new);
		XUANYUAN_SWORD = REGISTRY.register("xuanyuan_sword", XuanyuanSwordItem::new);
		ADEPTUS_GUN = REGISTRY.register("adeptus_gun", AdeptusGunItem::new);
		BIG_STONE = block(OneiricconceptModBlocks.BIG_STONE);
		BIG_ROCK = block(OneiricconceptModBlocks.BIG_ROCK);
		HONKAI_SHARD = REGISTRY.register("honkai_shard", HonkaiShardItem::new);
		LEGION_PSEUDO_CORE = REGISTRY.register("legion_pseudo_core", LegionPseudoCoreItem::new);
		LEGION_PSEUDO_SLIVER = REGISTRY.register("legion_pseudo_sliver", LegionPseudoSliverItem::new);
		HONKAI_SLIVER = REGISTRY.register("honkai_sliver", HonkaiSliverItem::new);
		OY_DUMPLING = REGISTRY.register("oy_dumpling", OyDumplingItem::new);
		DUMPLING = REGISTRY.register("dumpling", DumplingItem::new);
		OY_STUFFING = REGISTRY.register("oy_stuffing", OyStuffingItem::new);
		THE_ANOTHER_WORLD_LOG = block(OneiricconceptModBlocks.THE_ANOTHER_WORLD_LOG);
		STRIPPED_THE_ANOTHER_WORLD_LOG = block(OneiricconceptModBlocks.STRIPPED_THE_ANOTHER_WORLD_LOG);
		THE_ANOTHER_WORLD_SAPLING = block(OneiricconceptModBlocks.THE_ANOTHER_WORLD_SAPLING);
		DARK_XUANYUAN_SWORD = REGISTRY.register("dark_xuanyuan_sword", DarkXuanyuanSwordItem::new);
		THE_ANOTHER_WORLD_WOOD = block(OneiricconceptModBlocks.THE_ANOTHER_WORLD_WOOD);
		CONDENSED_MEMORIA_PIECE = REGISTRY.register("condensed_memoria_piece", CondensedMemoriaPieceItem::new);
		TAW_WOOD_BOX = REGISTRY.register("taw_wood_box", TAWWoodBoxItem::new);
		TAW_WOOD_LOOT = REGISTRY.register("taw_wood_loot", TAWWoodLootItem::new);
		MEMORIA_LOOT = REGISTRY.register("memoria_loot", MemoriaLootItem::new);
		MM_MUSHROOM = doubleBlock(OneiricconceptModBlocks.MM_MUSHROOM);
		MMMHIT = REGISTRY.register("mmmhit", MmmhitItem::new);
		BACTUS = block(OneiricconceptModBlocks.BACTUS);
		C_CACTUS = block(OneiricconceptModBlocks.C_CACTUS);
		GACTUS = block(OneiricconceptModBlocks.GACTUS);
		MACTUS = block(OneiricconceptModBlocks.MACTUS);
		RACTUS = block(OneiricconceptModBlocks.RACTUS);
		YACTUS = block(OneiricconceptModBlocks.YACTUS);
		SWORD_OF_BRILLIANT_VALOR = REGISTRY.register("sword_of_brilliant_valor", SwordOfBrilliantValorItem::new);
		THE_ANOTHER_WORLD_LEAVE = block(OneiricconceptModBlocks.THE_ANOTHER_WORLD_LEAVE);
		CRYSTAL_TURTLE_SPAWN_EGG = REGISTRY.register("crystal_turtle_spawn_egg", () -> new DeferredSpawnEggItem(OneiricconceptModEntities.CRYSTAL_TURTLE, -3342337, -16737844, new Item.Properties()));
		TNT_DISPENSER = block(OneiricconceptModBlocks.TNT_DISPENSER);
		WAFFLE = REGISTRY.register("waffle", WaffleItem::new);
		PRIMOGEM_WAFFLE = REGISTRY.register("primogem_waffle", PrimogemWaffleItem::new);
		D_XUANYUAN = REGISTRY.register("d_xuanyuan", DXuanyuanItem::new);
		SMALL_HERTA_CORE = REGISTRY.register("small_herta_core", SmallHertaCoreItem::new);
		SKY_WAFFLE = REGISTRY.register("sky_waffle", SkyWaffleItem::new);
		RESURRECTION_PELLET = REGISTRY.register("resurrection_pellet", ResurrectionPelletItem::new);
		SURPRISEBOXFORGOODORBAD = REGISTRY.register("surpriseboxforgoodorbad", SurpriseboxforgoodorbadItem::new);
		EXAMPLE = REGISTRY.register("example", ExampleItem::new);
		TOTEMLOOT = REGISTRY.register("totemloot", TotemlootItem::new);
		COMPRESS_TOTEMLOOT = REGISTRY.register("compress_totemloot", CompressTotemlootItem::new);
		BOSS_STONE_COIN_GUN = REGISTRY.register("boss_stone_coin_gun", BossStoneCoinGunItem::new);
		MORA_MAGAZINE = REGISTRY.register("mora_magazine", MoraMagazineItem::new);
		MORA_MAGAZINE_E_1 = REGISTRY.register("mora_magazine_e_1", MoraMagazineE1Item::new);
		BOSS_STONE_COIN_GUN_PLUS = REGISTRY.register("boss_stone_coin_gun_plus", BossStoneCoinGunPlusItem::new);
		PUBLIC_CLAMOR = REGISTRY.register("public_clamor", PublicClamorItem::new);
		PROPAGANDA_ARMY = REGISTRY.register("propaganda_army", PropagandaArmyItem::new);
		PROPAGANDA_ARMY_BLOCK = block(OneiricconceptModBlocks.PROPAGANDA_ARMY_BLOCK);
		A_PROPAGANDA_ARMY = REGISTRY.register("a_propaganda_army", APropagandaArmyItem::new);
		THUNDER_SWORD = block(OneiricconceptModBlocks.THUNDER_SWORD);
		PGC_PRESENT = block(OneiricconceptModBlocks.PGC_PRESENT);
		PRIMOGEM = block(OneiricconceptModBlocks.PRIMOGEM);
		PYRO_METAL = block(OneiricconceptModBlocks.PYRO_METAL);
		CAMERA = block(OneiricconceptModBlocks.CAMERA);
		SUSTENANCEANCHORITEM = REGISTRY.register("sustenanceanchoritem", SustenanceanchoritemItem::new);
		SUSTENANCEANCHOROFF = block(OneiricconceptModBlocks.SUSTENANCEANCHOROFF);
		SUSTENANCEANCHOR = block(OneiricconceptModBlocks.SUSTENANCEANCHOR);
		CRESCENT_METAL = block(OneiricconceptModBlocks.CRESCENT_METAL);
		REDMOON_METAL = block(OneiricconceptModBlocks.REDMOON_METAL);
		FULLMOON_METAL = block(OneiricconceptModBlocks.FULLMOON_METAL);
		TRASHMETAL = block(OneiricconceptModBlocks.TRASHMETAL);
		ELECTRO_METAL = block(OneiricconceptModBlocks.ELECTRO_METAL);
		HYDRO_METAL = block(OneiricconceptModBlocks.HYDRO_METAL);
		CRYO_METAL = block(OneiricconceptModBlocks.CRYO_METAL);
		DENDRO_METAL = block(OneiricconceptModBlocks.DENDRO_METAL);
		ANEMO_METAL = block(OneiricconceptModBlocks.ANEMO_METAL);
		GEO_METAL = block(OneiricconceptModBlocks.GEO_METAL);
		SUPERIMPOSER_CUSTOMMADE = block(OneiricconceptModBlocks.SUPERIMPOSER_CUSTOMMADE);
		HERTABOND = block(OneiricconceptModBlocks.HERTABOND);
		PYROSEALINGWAX = block(OneiricconceptModBlocks.PYROSEALINGWAX);
		ELECTROSEALINGWAX = block(OneiricconceptModBlocks.ELECTROSEALINGWAX);
		HYDROSEALINGWAX = block(OneiricconceptModBlocks.HYDROSEALINGWAX);
		CRYOSEALINGWAX = block(OneiricconceptModBlocks.CRYOSEALINGWAX);
		DENDROSEALINGWAX = block(OneiricconceptModBlocks.DENDROSEALINGWAX);
		ANEMO_SEALINGWAX = block(OneiricconceptModBlocks.ANEMO_SEALINGWAX);
		GEOSEALINGWAX = block(OneiricconceptModBlocks.GEOSEALINGWAX);
		AMBROSIAL_ARBOR_LOG = block(OneiricconceptModBlocks.AMBROSIAL_ARBOR_LOG);
		AMBROSIAL_ARBOR_LEAVE = block(OneiricconceptModBlocks.AMBROSIAL_ARBOR_LEAVE);
		IGNIS_AURELIAE = REGISTRY.register("ignis_aureliae", IgnisAureliaeItem::new);
		AURELIAE_PICKAXE = REGISTRY.register("aureliae_pickaxe", AureliaePickaxeItem::new);
		AURELIAE_AXE = REGISTRY.register("aureliae_axe", AureliaeAxeItem::new);
		AURELIAE_SWORD = REGISTRY.register("aureliae_sword", AureliaeSwordItem::new);
		AURELIAE_SHOVEL = REGISTRY.register("aureliae_shovel", AureliaeShovelItem::new);
		AURELIAE_HOE = REGISTRY.register("aureliae_hoe", AureliaeHoeItem::new);
		MOLTEN_METAL = REGISTRY.register("molten_metal", MoltenMetalItem::new);
		MOLTEN_METAL_BLOCK = block(OneiricconceptModBlocks.MOLTEN_METAL_BLOCK);
		PRIMOGEMFRUITBLOCK = block(OneiricconceptModBlocks.PRIMOGEMFRUITBLOCK);
		PRIMOGEMFRUIT = REGISTRY.register("primogemfruit", PrimogemfruitItem::new);
		AMBROSIAL_ARBOR_SAPLING = block(OneiricconceptModBlocks.AMBROSIAL_ARBOR_SAPLING);
		AMBROSIAL_ARBOR_PLANK = block(OneiricconceptModBlocks.AMBROSIAL_ARBOR_PLANK);
		HILTWOOD_FROM_THE_ARBOR = REGISTRY.register("hiltwood_from_the_arbor", HiltwoodFromTheArborItem::new);
		WAYFAREBLESSING = block(OneiricconceptModBlocks.WAYFAREBLESSING);
		HEARTOFTHEFROZENSEA = REGISTRY.register("heartofthefrozensea", HeartofthefrozenseaItem::new);
		HEARTOFTHESKYSEA = REGISTRY.register("heartoftheskysea", HeartoftheskyseaItem::new);
		HEARTOFTHEWARMSEA = REGISTRY.register("heartofthewarmsea", HeartofthewarmseaItem::new);
		HEARTOFTHEVASTSEA = REGISTRY.register("heartofthevastsea", HeartofthevastseaItem::new);
		FLOATING_CLOUD = block(OneiricconceptModBlocks.FLOATING_CLOUD);
		SALT = REGISTRY.register("salt", SaltItem::new);
		MILK = REGISTRY.register("milk", MilkItem::new);
		RED_BEAN_SOUP_FILLING_YUAN_XIAO = REGISTRY.register("red_bean_soup_filling_yuan_xiao", RedBeanSoupFillingYuanXiaoItem::new);
		SWEET_SESAME_FILLING_YUAN_XIAO = REGISTRY.register("sweet_sesame_filling_yuan_xiao", SweetSesameFillingYuanXiaoItem::new);
		GRILLED_OY_DUMPLING = REGISTRY.register("grilled_oy_dumpling", GrilledOyDumplingItem::new);
		GRILLED_DUMPLING = REGISTRY.register("grilled_dumpling", GrilledDumplingItem::new);
		SALT_DUST = REGISTRY.register("salt_dust", SaltDustItem::new);
		HUNGER = REGISTRY.register("hunger", HungerItem::new);
		AMBROSIAL_ARBOR_WOOD = block(OneiricconceptModBlocks.AMBROSIAL_ARBOR_WOOD);
		AMBERGRIS_CHEESE_SLIVER = REGISTRY.register("ambergris_cheese_sliver", AmbergrisCheeseSliverItem::new);
		DIVINE_ARROW_EMBERS = REGISTRY.register("divine_arrow_embers", DivineArrowEmbersItem::new);
		DEEP_MARROW_ROCK_SALT = REGISTRY.register("deep_marrow_rock_salt", DeepMarrowRockSaltItem::new);
		FRESH_SEEDOF_DAWN = block(OneiricconceptModBlocks.FRESH_SEEDOF_DAWN);
		DAWNLEAVES = block(OneiricconceptModBlocks.DAWNLEAVES);
		XIAO_LANTERN_RECYCLER = block(OneiricconceptModBlocks.XIAO_LANTERN_RECYCLER);
		HEARTOFTHEFISH = REGISTRY.register("heartofthefish", HeartofthefishItem::new);
		PHLOGISTONTANK = block(OneiricconceptModBlocks.PHLOGISTONTANK);
		PHLOGISTON_CRYSTAL = REGISTRY.register("phlogiston_crystal", PhlogistonCrystalItem::new);
		PHLOGISTON = REGISTRY.register("phlogiston", PhlogistonItem::new);
		FISHCAKE = REGISTRY.register("fishcake", FishcakeItem::new);
		WAYFARE_CAKE_SLICES = REGISTRY.register("wayfare_cake_slices", WayfareCakeSlicesItem::new);
		PRIMOGEMCRAFTWIKI = REGISTRY.register("primogemcraftwiki", PrimogemcraftwikiItem::new);
		WILDERNESS_ROD = REGISTRY.register("wilderness_rod", WildernessRodItem::new);
		CAMERAPINK = block(OneiricconceptModBlocks.CAMERAPINK);
		SWEETFLOWER = block(OneiricconceptModBlocks.SWEETFLOWER);
		ICE_FRESH_RAW_FROSTWEAVE_SALMON_SLICES = REGISTRY.register("ice_fresh_raw_frostweave_salmon_slices", IceFreshRawFrostweaveSalmonSlicesItem::new);
		XUANYUAN_ARROW = REGISTRY.register("xuanyuan_arrow", XuanyuanArrowItem::new);
		FRUITPASTEBAIT = REGISTRY.register("fruitpastebait", FruitpastebaitItem::new);
		SWEETFLOWERMEDAKA = REGISTRY.register("sweetflowermedaka", SweetflowermedakaItem::new);
		FISH = REGISTRY.register("fish", PlumpFishItem::new);
		MEDAKA = REGISTRY.register("medaka", MedakaItem::new);
		GLAZEMEDAKA = REGISTRY.register("glazemedaka", GlazemedakaItem::new);
		AIZENMEDAKA = REGISTRY.register("aizenmedaka", AizenmedakaItem::new);
		VIRTUAL_PARTICLE = REGISTRY.register("virtual_particle", VirtualParticleItem::new);
		SOLID_WATER = REGISTRY.register("solid_water", SolidWaterItem::new);
		CAMO_PAINT = REGISTRY.register("camo_paint", CamoPaintItem::new);
		ENERGY_DRINK = REGISTRY.register("energy_drink", EnergyDrinkItem::new);
		ENERGY_DRINK_PRIMOGEM = REGISTRY.register("energy_drink_primogem", EnergyDrinkPrimogemItem::new);
		ENERGY_DRINK_SUGAR_FREE = REGISTRY.register("energy_drink_sugar_free", EnergyDrinkSugarFreeItem::new);
		TREE_BARKOF_ERUDITION = REGISTRY.register("tree_barkof_erudition", TreeBarkofEruditionItem::new);
		PUNITIVE_ENERGY = REGISTRY.register("punitive_energy", PunitiveEnergyItem::new);
		MORA_BOW = REGISTRY.register("mora_bow", MoraBowItem::new);
		THIEF_S_INSTINCT = REGISTRY.register("thief_s_instinct", ThiefSInstinctItem::new);
		USURPER_S_SCHEME = REGISTRY.register("usurper_s_scheme", UsurperSSchemeItem::new);
		CONQUEROR_S_WILL = REGISTRY.register("conqueror_s_will", ConquerorSWillItem::new);
		ADEPTUSTOOL = REGISTRY.register("adeptustool", TesttoolItem::new);
		RAINBOW_CACTUS_BALL = block(OneiricconceptModBlocks.RAINBOW_CACTUS_BALL);
		SKIP_TOOL = REGISTRY.register("skip_tool", SkipToolItem::new);
		DREAMY_CONE = REGISTRY.register("dreamy_cone", DreamyConeItem::new);
		EXHAUSTEDPRIMOGEM = block(OneiricconceptModBlocks.EXHAUSTEDPRIMOGEM);
		PRIMOGEMSTORMGLASS = block(OneiricconceptModBlocks.PRIMOGEMSTORMGLASS);
		STARDUST_BASEBALLER = REGISTRY.register("stardust_baseballer", StardustBaseballerItem::new);
		CRYSTALGENERATOR = block(OneiricconceptModBlocks.CRYSTALGENERATOR);
		CULLINAN = REGISTRY.register("cullinan", CullinanItem::new);
		NEST = block(OneiricconceptModBlocks.NEST);
		ENGINEERINGANTIMATTERBOMBBLOCK = block(OneiricconceptModBlocks.ENGINEERINGANTIMATTERBOMBBLOCK);
		CRESCENTMOONORE = block(OneiricconceptModBlocks.CRESCENTMOONORE);
		REDMOONORE = block(OneiricconceptModBlocks.REDMOONORE);
		FULLMOONORE = block(OneiricconceptModBlocks.FULLMOONORE);
		RAWCRESCENTMOONORE = REGISTRY.register("rawcrescentmoonore", RawcrescentmoonoreItem::new);
		RAWREDMOONORE = REGISTRY.register("rawredmoonore", RawredmoonoreItem::new);
		RAWFULLMOONORE = REGISTRY.register("rawfullmoonore", RawfullmoonoreItem::new);
		THEANOTHERWORLDMOONINGOT = block(OneiricconceptModBlocks.THEANOTHERWORLDMOONINGOT);
		WHITE_MOONLIGHT_ABSORBER = block(OneiricconceptModBlocks.WHITE_MOONLIGHT_ABSORBER);
		FINE_TEA_FULL_MOON = REGISTRY.register("fine_tea_full_moon", FineTeaFullMoonItem::new);
		CHENYU_ADEPTEA = REGISTRY.register("chenyu_adeptea", ChenyuAdepteaItem::new);
		CHENYU_ADEPTEA_TREE = block(OneiricconceptModBlocks.CHENYU_ADEPTEA_TREE);
		CHENYU_ADEPTEA_SEEDLING = block(OneiricconceptModBlocks.CHENYU_ADEPTEA_SEEDLING);
		THE_BOON_OF_THE_ELDER_TREE = REGISTRY.register("the_boon_of_the_elder_tree", TheBoonOfTheElderTreeItem::new);
		PYRO_BOOMYAM = REGISTRY.register("pyro_boomyam", BoomyampyroItem::new);
		CELEBRATORY_XIAO_LANTERN = block(OneiricconceptModBlocks.CELEBRATORY_XIAO_LANTERN);
		DENDRO_LAUNCH = REGISTRY.register("dendro_launch", DendroLaunchItem::new);
		BOOM_BLOSSOMS_CRYO = block(OneiricconceptModBlocks.BOOM_BLOSSOMS_CRYO);
		BOOM_BLOSSOMS_DENDRO = block(OneiricconceptModBlocks.BOOM_BLOSSOMS_DENDRO);
		BOOM_BLOSSOMS_ELECTRO = block(OneiricconceptModBlocks.BOOM_BLOSSOMS_ELECTRO);
		BOOM_BLOSSOMS_HYDRO = block(OneiricconceptModBlocks.BOOM_BLOSSOMS_HYDRO);
		CRYO_BOOMYAM = REGISTRY.register("cryo_boomyam", CryoBoomyamItem::new);
		DENDRO_BOOMYAM = REGISTRY.register("dendro_boomyam", DendroBoomyamItem::new);
		ELECTRO_BOOMYAM = REGISTRY.register("electro_boomyam", ElectroBoomyamItem::new);
		HYDRO_BOOMYAM = REGISTRY.register("hydro_boomyam", HydroBoomyamItem::new);
		TOASTPIZZA = REGISTRY.register("toastpizza", ToastpizzaItem::new);
		TOAST_TOAST_PIZZA = REGISTRY.register("toast_toast_pizza", ToastToastPizzaItem::new);
	}

	// Start of user code block custom items
	// End of user code block custom items
	@SubscribeEvent
	public static void registerCapabilities(RegisterCapabilitiesEvent event) {
		event.registerItem(Capabilities.FluidHandler.ITEM, (stack, context) -> new FluidBucketWrapper(stack), MEMORIA_BUCKET.get());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), properties));
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block) {
		return doubleBlock(block, new Item.Properties());
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), properties));
	}

	@EventBusSubscriber(Dist.CLIENT)
	public static class ItemsClientSideHandler {
		@SubscribeEvent
		@OnlyIn(Dist.CLIENT)
		public static void clientLoad(FMLClientSetupEvent event) {
			event.enqueueWork(() -> {
				ItemProperties.register(ADEPTUS_GUN.get(), ResourceLocation.parse("oneiricconcept:adeptus_gun_mode"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) VastmodeProcedure.execute(itemStackToRender));
				ItemProperties.register(MORA_MAGAZINE.get(), ResourceLocation.parse("oneiricconcept:mora_magazine_textures"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) TexturesProcedure.execute(itemStackToRender));
				ItemProperties.register(MORA_MAGAZINE_E_1.get(), ResourceLocation.parse("oneiricconcept:mora_magazine_e_1_textures"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) TexturesProcedure.execute(itemStackToRender));
				ItemProperties.register(HEARTOFTHEVASTSEA.get(), ResourceLocation.parse("oneiricconcept:heartofthevastsea_itemmode"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) VastmodeProcedure.execute(itemStackToRender));
				ItemProperties.register(MORA_BOW.get(), ResourceLocation.parse("oneiricconcept:mora_bow_pull"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) BowPullProcedure.execute(entity, itemStackToRender));
				ItemProperties.register(ADEPTUSTOOL.get(), ResourceLocation.parse("oneiricconcept:adeptustool_test"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) TexturesProcedure.execute(itemStackToRender));
				ItemProperties.register(STARDUST_BASEBALLER.get(), ResourceLocation.parse("oneiricconcept:stardust_baseballer_textures"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) TexturesProcedure.execute(itemStackToRender));
			});
		}
	}
}