
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.oneiricconcept.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.common.DeferredSpawnEggItem;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.OnlyIn;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.client.renderer.item.ItemProperties;

import net.mcreator.oneiricconcept.procedures.VastmodeProcedure;
import net.mcreator.oneiricconcept.item.XuanyuanSwordItem;
import net.mcreator.oneiricconcept.item.WaffleItem;
import net.mcreator.oneiricconcept.item.TotemlootItem;
import net.mcreator.oneiricconcept.item.TAWWoodLootItem;
import net.mcreator.oneiricconcept.item.TAWWoodBoxItem;
import net.mcreator.oneiricconcept.item.SwordOfBrilliantValorItem;
import net.mcreator.oneiricconcept.item.SweetSesameFillingYuanXiaoItem;
import net.mcreator.oneiricconcept.item.SustenanceanchoritemItem;
import net.mcreator.oneiricconcept.item.SurpriseboxforgoodorbadItem;
import net.mcreator.oneiricconcept.item.SunStartCanItem;
import net.mcreator.oneiricconcept.item.StuffingItem;
import net.mcreator.oneiricconcept.item.SmokeSausageItem;
import net.mcreator.oneiricconcept.item.SmallHertaCoreItem;
import net.mcreator.oneiricconcept.item.SkyWaffleItem;
import net.mcreator.oneiricconcept.item.SausageItem;
import net.mcreator.oneiricconcept.item.SaltItem;
import net.mcreator.oneiricconcept.item.SaltDustItem;
import net.mcreator.oneiricconcept.item.S2tuffingItem;
import net.mcreator.oneiricconcept.item.S2mokeSausageItem;
import net.mcreator.oneiricconcept.item.S2ausageItem;
import net.mcreator.oneiricconcept.item.ResurrectionPelletItem;
import net.mcreator.oneiricconcept.item.RedBeanSoupFillingYuanXiaoItem;
import net.mcreator.oneiricconcept.item.PublicClamorItem;
import net.mcreator.oneiricconcept.item.PropagandaArmyItem;
import net.mcreator.oneiricconcept.item.PrimogemsSausageItem;
import net.mcreator.oneiricconcept.item.PrimogemfruitItem;
import net.mcreator.oneiricconcept.item.PrimogemWaffleItem;
import net.mcreator.oneiricconcept.item.OyStuffingItem;
import net.mcreator.oneiricconcept.item.OyDumplingItem;
import net.mcreator.oneiricconcept.item.OneiricShardItem;
import net.mcreator.oneiricconcept.item.MoraSausageItem;
import net.mcreator.oneiricconcept.item.MoraMagazineN3Item;
import net.mcreator.oneiricconcept.item.MoraMagazineN2Item;
import net.mcreator.oneiricconcept.item.MoraMagazineItem;
import net.mcreator.oneiricconcept.item.MoraMagazineE3Item;
import net.mcreator.oneiricconcept.item.MoraMagazineE2Item;
import net.mcreator.oneiricconcept.item.MoraMagazineE1Item;
import net.mcreator.oneiricconcept.item.MoltenMetalItem;
import net.mcreator.oneiricconcept.item.MmmhitItem;
import net.mcreator.oneiricconcept.item.MilkItem;
import net.mcreator.oneiricconcept.item.MemoryBubbleItem;
import net.mcreator.oneiricconcept.item.MemoriaPieceItem;
import net.mcreator.oneiricconcept.item.MemoriaLootItem;
import net.mcreator.oneiricconcept.item.MemoriaItem;
import net.mcreator.oneiricconcept.item.LessRedstonePowderItem;
import net.mcreator.oneiricconcept.item.LegionPseudoSliverItem;
import net.mcreator.oneiricconcept.item.LegionPseudoCoreItem;
import net.mcreator.oneiricconcept.item.IgnisAureliaeItem;
import net.mcreator.oneiricconcept.item.HungerItem;
import net.mcreator.oneiricconcept.item.HonkaiSliverItem;
import net.mcreator.oneiricconcept.item.HonkaiShardItem;
import net.mcreator.oneiricconcept.item.HiltwoodFromTheArborItem;
import net.mcreator.oneiricconcept.item.HeartofthewarmseaItem;
import net.mcreator.oneiricconcept.item.HeartofthevastseaItem;
import net.mcreator.oneiricconcept.item.HeartoftheskyseaItem;
import net.mcreator.oneiricconcept.item.HeartofthefrozenseaItem;
import net.mcreator.oneiricconcept.item.GrilledOyDumplingItem;
import net.mcreator.oneiricconcept.item.GrilledDumplingItem;
import net.mcreator.oneiricconcept.item.ExampleItem;
import net.mcreator.oneiricconcept.item.DumplingItem;
import net.mcreator.oneiricconcept.item.DreamdiveCanItem;
import net.mcreator.oneiricconcept.item.DivineArrowEmbersItem;
import net.mcreator.oneiricconcept.item.DarkXuanyuanSwordItem;
import net.mcreator.oneiricconcept.item.DXuanyuanItem;
import net.mcreator.oneiricconcept.item.CondensedMemoriaPieceItem;
import net.mcreator.oneiricconcept.item.CompressTotemlootItem;
import net.mcreator.oneiricconcept.item.CloudBottleItem;
import net.mcreator.oneiricconcept.item.BossStoneCoinGunPlusItem;
import net.mcreator.oneiricconcept.item.BossStoneCoinGunItem;
import net.mcreator.oneiricconcept.item.BelobogSausageItem;
import net.mcreator.oneiricconcept.item.B2elobogSausageItem;
import net.mcreator.oneiricconcept.item.AureliaeSwordItem;
import net.mcreator.oneiricconcept.item.AureliaeShovelItem;
import net.mcreator.oneiricconcept.item.AureliaePickaxeItem;
import net.mcreator.oneiricconcept.item.AureliaeHoeItem;
import net.mcreator.oneiricconcept.item.AureliaeAxeItem;
import net.mcreator.oneiricconcept.item.AmbergrisCheeseSliverItem;
import net.mcreator.oneiricconcept.item.AdeptusGunItem;
import net.mcreator.oneiricconcept.item.APropagandaArmyItem;
import net.mcreator.oneiricconcept.OneiricconceptMod;

public class OneiricconceptModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(OneiricconceptMod.MODID);
	public static final DeferredItem<Item> SAUSAGE = REGISTRY.register("sausage", SausageItem::new);
	public static final DeferredItem<Item> SMOKE_SAUSAGE = REGISTRY.register("smoke_sausage", SmokeSausageItem::new);
	public static final DeferredItem<Item> BELOBOG_SAUSAGE = REGISTRY.register("belobog_sausage", BelobogSausageItem::new);
	public static final DeferredItem<Item> S_2AUSAGE = REGISTRY.register("s_2ausage", S2ausageItem::new);
	public static final DeferredItem<Item> S_2MOKE_SAUSAGE = REGISTRY.register("s_2moke_sausage", S2mokeSausageItem::new);
	public static final DeferredItem<Item> B_2ELOBOG_SAUSAGE = REGISTRY.register("b_2elobog_sausage", B2elobogSausageItem::new);
	public static final DeferredItem<Item> STUFFING = REGISTRY.register("stuffing", StuffingItem::new);
	public static final DeferredItem<Item> S_2TUFFING = REGISTRY.register("s_2tuffing", S2tuffingItem::new);
	public static final DeferredItem<Item> GEOMARROW_RADIATOR = block(OneiricconceptModBlocks.GEOMARROW_RADIATOR);
	public static final DeferredItem<Item> ONEIRIC_SHARD = REGISTRY.register("oneiric_shard", OneiricShardItem::new);
	public static final DeferredItem<Item> MORA_SAUSAGE = REGISTRY.register("mora_sausage", MoraSausageItem::new);
	public static final DeferredItem<Item> PRIMOGEMS_SAUSAGE = REGISTRY.register("primogems_sausage", PrimogemsSausageItem::new);
	public static final DeferredItem<Item> BOOM_BLOSSOMS_PYRO = block(OneiricconceptModBlocks.BOOM_BLOSSOMS_PYRO);
	public static final DeferredItem<Item> BANANA_MUSHROOM = block(OneiricconceptModBlocks.BANANA_MUSHROOM);
	public static final DeferredItem<Item> BANANA_MUSHROOM_BOCK = block(OneiricconceptModBlocks.BANANA_MUSHROOM_BOCK);
	public static final DeferredItem<Item> ELEMENTS_CRYSTAL_ORE = block(OneiricconceptModBlocks.ELEMENTS_CRYSTAL_ORE);
	public static final DeferredItem<Item> NAGADUS_EMERALD_ORE = block(OneiricconceptModBlocks.NAGADUS_EMERALD_ORE);
	public static final DeferredItem<Item> SHIVADA_JADE_ORE = block(OneiricconceptModBlocks.SHIVADA_JADE_ORE);
	public static final DeferredItem<Item> VAJRADA_AMETHYST_ORE = block(OneiricconceptModBlocks.VAJRADA_AMETHYST_ORE);
	public static final DeferredItem<Item> VARUNADA_LAZURITE_ORE = block(OneiricconceptModBlocks.VARUNADA_LAZURITE_ORE);
	public static final DeferredItem<Item> CLOUD = block(OneiricconceptModBlocks.CLOUD);
	public static final DeferredItem<Item> PRITHIVA_TOPAZ_ORE = block(OneiricconceptModBlocks.PRITHIVA_TOPAZ_ORE);
	public static final DeferredItem<Item> VAYUDA_TURQUOISE_ORE = block(OneiricconceptModBlocks.VAYUDA_TURQUOISE_ORE);
	public static final DeferredItem<Item> AGNIDUS_AGATE_ORE = block(OneiricconceptModBlocks.AGNIDUS_AGATE_ORE);
	public static final DeferredItem<Item> CLOUD_BOTTLE = REGISTRY.register("cloud_bottle", CloudBottleItem::new);
	public static final DeferredItem<Item> DREAMDIVE_CAN = REGISTRY.register("dreamdive_can", DreamdiveCanItem::new);
	public static final DeferredItem<Item> SUN_START_CAN = REGISTRY.register("sun_start_can", SunStartCanItem::new);
	public static final DeferredItem<Item> MEMORIA_BUCKET = REGISTRY.register("memoria_bucket", MemoriaItem::new);
	public static final DeferredItem<Item> MEMORY_BUBBLE = REGISTRY.register("memory_bubble", MemoryBubbleItem::new);
	public static final DeferredItem<Item> MEMORIA_PIECE = REGISTRY.register("memoria_piece", MemoriaPieceItem::new);
	public static final DeferredItem<Item> XUANYUAN_SWORD = REGISTRY.register("xuanyuan_sword", XuanyuanSwordItem::new);
	public static final DeferredItem<Item> ADEPTUS_GUN = REGISTRY.register("adeptus_gun", AdeptusGunItem::new);
	public static final DeferredItem<Item> BIG_STONE = block(OneiricconceptModBlocks.BIG_STONE);
	public static final DeferredItem<Item> BIG_ROCK = block(OneiricconceptModBlocks.BIG_ROCK);
	public static final DeferredItem<Item> HONKAI_SHARD = REGISTRY.register("honkai_shard", HonkaiShardItem::new);
	public static final DeferredItem<Item> LEGION_PSEUDO_CORE = REGISTRY.register("legion_pseudo_core", LegionPseudoCoreItem::new);
	public static final DeferredItem<Item> LEGION_PSEUDO_SLIVER = REGISTRY.register("legion_pseudo_sliver", LegionPseudoSliverItem::new);
	public static final DeferredItem<Item> HONKAI_SLIVER = REGISTRY.register("honkai_sliver", HonkaiSliverItem::new);
	public static final DeferredItem<Item> OY_DUMPLING = REGISTRY.register("oy_dumpling", OyDumplingItem::new);
	public static final DeferredItem<Item> DUMPLING = REGISTRY.register("dumpling", DumplingItem::new);
	public static final DeferredItem<Item> OY_STUFFING = REGISTRY.register("oy_stuffing", OyStuffingItem::new);
	public static final DeferredItem<Item> THE_ANOTHER_WORLD_LOG = block(OneiricconceptModBlocks.THE_ANOTHER_WORLD_LOG);
	public static final DeferredItem<Item> STRIPPED_THE_ANOTHER_WORLD_LOG = block(OneiricconceptModBlocks.STRIPPED_THE_ANOTHER_WORLD_LOG);
	public static final DeferredItem<Item> THE_ANOTHER_WORLD_SAPLING = block(OneiricconceptModBlocks.THE_ANOTHER_WORLD_SAPLING);
	public static final DeferredItem<Item> DARK_XUANYUAN_SWORD = REGISTRY.register("dark_xuanyuan_sword", DarkXuanyuanSwordItem::new);
	public static final DeferredItem<Item> THE_ANOTHER_WORLD_WOOD = block(OneiricconceptModBlocks.THE_ANOTHER_WORLD_WOOD);
	public static final DeferredItem<Item> CONDENSED_MEMORIA_PIECE = REGISTRY.register("condensed_memoria_piece", CondensedMemoriaPieceItem::new);
	public static final DeferredItem<Item> TAW_WOOD_BOX = REGISTRY.register("taw_wood_box", TAWWoodBoxItem::new);
	public static final DeferredItem<Item> TAW_WOOD_LOOT = REGISTRY.register("taw_wood_loot", TAWWoodLootItem::new);
	public static final DeferredItem<Item> MEMORIA_LOOT = REGISTRY.register("memoria_loot", MemoriaLootItem::new);
	public static final DeferredItem<Item> MM_MUSHROOM = doubleBlock(OneiricconceptModBlocks.MM_MUSHROOM);
	public static final DeferredItem<Item> MMMHIT = REGISTRY.register("mmmhit", MmmhitItem::new);
	public static final DeferredItem<Item> BACTUS = block(OneiricconceptModBlocks.BACTUS);
	public static final DeferredItem<Item> C_CACTUS = block(OneiricconceptModBlocks.C_CACTUS);
	public static final DeferredItem<Item> GACTUS = block(OneiricconceptModBlocks.GACTUS);
	public static final DeferredItem<Item> MACTUS = block(OneiricconceptModBlocks.MACTUS);
	public static final DeferredItem<Item> RACTUS = block(OneiricconceptModBlocks.RACTUS);
	public static final DeferredItem<Item> YACTUS = block(OneiricconceptModBlocks.YACTUS);
	public static final DeferredItem<Item> SWORD_OF_BRILLIANT_VALOR = REGISTRY.register("sword_of_brilliant_valor", SwordOfBrilliantValorItem::new);
	public static final DeferredItem<Item> THE_ANOTHER_WORLD_LEAVE = block(OneiricconceptModBlocks.THE_ANOTHER_WORLD_LEAVE);
	public static final DeferredItem<Item> CRYSTAL_TURTLE_SPAWN_EGG = REGISTRY.register("crystal_turtle_spawn_egg", () -> new DeferredSpawnEggItem(OneiricconceptModEntities.CRYSTAL_TURTLE, -3342337, -16737844, new Item.Properties()));
	public static final DeferredItem<Item> TNT_DISPENSER = block(OneiricconceptModBlocks.TNT_DISPENSER);
	public static final DeferredItem<Item> WAFFLE = REGISTRY.register("waffle", WaffleItem::new);
	public static final DeferredItem<Item> PRIMOGEM_WAFFLE = REGISTRY.register("primogem_waffle", PrimogemWaffleItem::new);
	public static final DeferredItem<Item> D_XUANYUAN = REGISTRY.register("d_xuanyuan", DXuanyuanItem::new);
	public static final DeferredItem<Item> SMALL_HERTA_CORE = REGISTRY.register("small_herta_core", SmallHertaCoreItem::new);
	public static final DeferredItem<Item> SKY_WAFFLE = REGISTRY.register("sky_waffle", SkyWaffleItem::new);
	public static final DeferredItem<Item> RESURRECTION_PELLET = REGISTRY.register("resurrection_pellet", ResurrectionPelletItem::new);
	public static final DeferredItem<Item> SURPRISEBOXFORGOODORBAD = REGISTRY.register("surpriseboxforgoodorbad", SurpriseboxforgoodorbadItem::new);
	public static final DeferredItem<Item> EXAMPLE = REGISTRY.register("example", ExampleItem::new);
	public static final DeferredItem<Item> TOTEMLOOT = REGISTRY.register("totemloot", TotemlootItem::new);
	public static final DeferredItem<Item> COMPRESS_TOTEMLOOT = REGISTRY.register("compress_totemloot", CompressTotemlootItem::new);
	public static final DeferredItem<Item> BOSS_STONE_COIN_GUN = REGISTRY.register("boss_stone_coin_gun", BossStoneCoinGunItem::new);
	public static final DeferredItem<Item> MORA_MAGAZINE = REGISTRY.register("mora_magazine", MoraMagazineItem::new);
	public static final DeferredItem<Item> MORA_MAGAZINE_N_2 = REGISTRY.register("mora_magazine_n_2", MoraMagazineN2Item::new);
	public static final DeferredItem<Item> MORA_MAGAZINE_N_3 = REGISTRY.register("mora_magazine_n_3", MoraMagazineN3Item::new);
	public static final DeferredItem<Item> MORA_MAGAZINE_E_1 = REGISTRY.register("mora_magazine_e_1", MoraMagazineE1Item::new);
	public static final DeferredItem<Item> MORA_MAGAZINE_E_2 = REGISTRY.register("mora_magazine_e_2", MoraMagazineE2Item::new);
	public static final DeferredItem<Item> MORA_MAGAZINE_E_3 = REGISTRY.register("mora_magazine_e_3", MoraMagazineE3Item::new);
	public static final DeferredItem<Item> BOSS_STONE_COIN_GUN_PLUS = REGISTRY.register("boss_stone_coin_gun_plus", BossStoneCoinGunPlusItem::new);
	public static final DeferredItem<Item> PUBLIC_CLAMOR = REGISTRY.register("public_clamor", PublicClamorItem::new);
	public static final DeferredItem<Item> PROPAGANDA_ARMY = REGISTRY.register("propaganda_army", PropagandaArmyItem::new);
	public static final DeferredItem<Item> PROPAGANDA_ARMY_BLOCK = block(OneiricconceptModBlocks.PROPAGANDA_ARMY_BLOCK);
	public static final DeferredItem<Item> A_PROPAGANDA_ARMY = REGISTRY.register("a_propaganda_army", APropagandaArmyItem::new);
	public static final DeferredItem<Item> LESS_REDSTONE_POWDER = REGISTRY.register("less_redstone_powder", LessRedstonePowderItem::new);
	public static final DeferredItem<Item> THUNDER_SWORD = block(OneiricconceptModBlocks.THUNDER_SWORD);
	public static final DeferredItem<Item> PGC_PRESENT = block(OneiricconceptModBlocks.PGC_PRESENT);
	public static final DeferredItem<Item> PGC_PG1 = block(OneiricconceptModBlocks.PGC_PG1);
	public static final DeferredItem<Item> PGC_PG2 = block(OneiricconceptModBlocks.PGC_PG2);
	public static final DeferredItem<Item> PGC_PG3 = block(OneiricconceptModBlocks.PGC_PG3);
	public static final DeferredItem<Item> PGC_PG4 = block(OneiricconceptModBlocks.PGC_PG4);
	public static final DeferredItem<Item> PGC_PG5 = block(OneiricconceptModBlocks.PGC_PG5);
	public static final DeferredItem<Item> PGC_PG6 = block(OneiricconceptModBlocks.PGC_PG6);
	public static final DeferredItem<Item> PGC_PG7 = block(OneiricconceptModBlocks.PGC_PG7);
	public static final DeferredItem<Item> AGNID_1 = block(OneiricconceptModBlocks.AGNID_1);
	public static final DeferredItem<Item> AGNID_2 = block(OneiricconceptModBlocks.AGNID_2);
	public static final DeferredItem<Item> AGNID_3 = block(OneiricconceptModBlocks.AGNID_3);
	public static final DeferredItem<Item> AGNID_4 = block(OneiricconceptModBlocks.AGNID_4);
	public static final DeferredItem<Item> AGNID_5 = block(OneiricconceptModBlocks.AGNID_5);
	public static final DeferredItem<Item> AGNID_6 = block(OneiricconceptModBlocks.AGNID_6);
	public static final DeferredItem<Item> AGNID_7 = block(OneiricconceptModBlocks.AGNID_7);
	public static final DeferredItem<Item> AGNID_8 = block(OneiricconceptModBlocks.AGNID_8);
	public static final DeferredItem<Item> AGNID_9 = block(OneiricconceptModBlocks.AGNID_9);
	public static final DeferredItem<Item> AGNID_10 = block(OneiricconceptModBlocks.AGNID_10);
	public static final DeferredItem<Item> CAMERA = block(OneiricconceptModBlocks.CAMERA);
	public static final DeferredItem<Item> SUSTENANCEANCHORITEM = REGISTRY.register("sustenanceanchoritem", SustenanceanchoritemItem::new);
	public static final DeferredItem<Item> SUSTENANCEANCHOROFF = block(OneiricconceptModBlocks.SUSTENANCEANCHOROFF);
	public static final DeferredItem<Item> SUSTENANCEANCHOR = block(OneiricconceptModBlocks.SUSTENANCEANCHOR);
	public static final DeferredItem<Item> NEWMO_1 = block(OneiricconceptModBlocks.NEWMO_1);
	public static final DeferredItem<Item> NEWMO_2 = block(OneiricconceptModBlocks.NEWMO_2);
	public static final DeferredItem<Item> NEWMO_3 = block(OneiricconceptModBlocks.NEWMO_3);
	public static final DeferredItem<Item> NEWMO_4 = block(OneiricconceptModBlocks.NEWMO_4);
	public static final DeferredItem<Item> NEWMO_7 = block(OneiricconceptModBlocks.NEWMO_7);
	public static final DeferredItem<Item> NEWMO_5 = block(OneiricconceptModBlocks.NEWMO_5);
	public static final DeferredItem<Item> NEWMO_6 = block(OneiricconceptModBlocks.NEWMO_6);
	public static final DeferredItem<Item> NEWMO_8 = block(OneiricconceptModBlocks.NEWMO_8);
	public static final DeferredItem<Item> NEWMO_9 = block(OneiricconceptModBlocks.NEWMO_9);
	public static final DeferredItem<Item> NEWMO_10 = block(OneiricconceptModBlocks.NEWMO_10);
	public static final DeferredItem<Item> REDMO_1 = block(OneiricconceptModBlocks.REDMO_1);
	public static final DeferredItem<Item> REDMO_2 = block(OneiricconceptModBlocks.REDMO_2);
	public static final DeferredItem<Item> REDMO_3 = block(OneiricconceptModBlocks.REDMO_3);
	public static final DeferredItem<Item> REDMO_4 = block(OneiricconceptModBlocks.REDMO_4);
	public static final DeferredItem<Item> REDMO_7 = block(OneiricconceptModBlocks.REDMO_7);
	public static final DeferredItem<Item> FULMO_1 = block(OneiricconceptModBlocks.FULMO_1);
	public static final DeferredItem<Item> FULMO_2 = block(OneiricconceptModBlocks.FULMO_2);
	public static final DeferredItem<Item> FULMO_3 = block(OneiricconceptModBlocks.FULMO_3);
	public static final DeferredItem<Item> FULMO_4 = block(OneiricconceptModBlocks.FULMO_4);
	public static final DeferredItem<Item> FULMO_7 = block(OneiricconceptModBlocks.FULMO_7);
	public static final DeferredItem<Item> LIRON_1 = block(OneiricconceptModBlocks.LIRON_1);
	public static final DeferredItem<Item> LIRON_2 = block(OneiricconceptModBlocks.LIRON_2);
	public static final DeferredItem<Item> LIRON_3 = block(OneiricconceptModBlocks.LIRON_3);
	public static final DeferredItem<Item> LIRON_4 = block(OneiricconceptModBlocks.LIRON_4);
	public static final DeferredItem<Item> LIRON_7 = block(OneiricconceptModBlocks.LIRON_7);
	public static final DeferredItem<Item> ELECT_1 = block(OneiricconceptModBlocks.ELECT_1);
	public static final DeferredItem<Item> ELECT_2 = block(OneiricconceptModBlocks.ELECT_2);
	public static final DeferredItem<Item> ELECT_3 = block(OneiricconceptModBlocks.ELECT_3);
	public static final DeferredItem<Item> ELECT_4 = block(OneiricconceptModBlocks.ELECT_4);
	public static final DeferredItem<Item> ELECT_7 = block(OneiricconceptModBlocks.ELECT_7);
	public static final DeferredItem<Item> HYDRO_1 = block(OneiricconceptModBlocks.HYDRO_1);
	public static final DeferredItem<Item> HYDRO_2 = block(OneiricconceptModBlocks.HYDRO_2);
	public static final DeferredItem<Item> HYDRO_3 = block(OneiricconceptModBlocks.HYDRO_3);
	public static final DeferredItem<Item> HYDRO_4 = block(OneiricconceptModBlocks.HYDRO_4);
	public static final DeferredItem<Item> HYDRO_7 = block(OneiricconceptModBlocks.HYDRO_7);
	public static final DeferredItem<Item> CRYOO_1 = block(OneiricconceptModBlocks.CRYOO_1);
	public static final DeferredItem<Item> CRYOO_2 = block(OneiricconceptModBlocks.CRYOO_2);
	public static final DeferredItem<Item> CRYOO_3 = block(OneiricconceptModBlocks.CRYOO_3);
	public static final DeferredItem<Item> CRYOO_4 = block(OneiricconceptModBlocks.CRYOO_4);
	public static final DeferredItem<Item> CRYOO_7 = block(OneiricconceptModBlocks.CRYOO_7);
	public static final DeferredItem<Item> DENDR_1 = block(OneiricconceptModBlocks.DENDR_1);
	public static final DeferredItem<Item> DENDR_2 = block(OneiricconceptModBlocks.DENDR_2);
	public static final DeferredItem<Item> DENDR_3 = block(OneiricconceptModBlocks.DENDR_3);
	public static final DeferredItem<Item> DENDR_4 = block(OneiricconceptModBlocks.DENDR_4);
	public static final DeferredItem<Item> DENDR_7 = block(OneiricconceptModBlocks.DENDR_7);
	public static final DeferredItem<Item> ANEMO_1 = block(OneiricconceptModBlocks.ANEMO_1);
	public static final DeferredItem<Item> ANEMO_2 = block(OneiricconceptModBlocks.ANEMO_2);
	public static final DeferredItem<Item> ANEMO_3 = block(OneiricconceptModBlocks.ANEMO_3);
	public static final DeferredItem<Item> ANEMO_4 = block(OneiricconceptModBlocks.ANEMO_4);
	public static final DeferredItem<Item> ANEMO_7 = block(OneiricconceptModBlocks.ANEMO_7);
	public static final DeferredItem<Item> GEOOO_1 = block(OneiricconceptModBlocks.GEOOO_1);
	public static final DeferredItem<Item> GEOOO_2 = block(OneiricconceptModBlocks.GEOOO_2);
	public static final DeferredItem<Item> GEOOO_3 = block(OneiricconceptModBlocks.GEOOO_3);
	public static final DeferredItem<Item> GEOOO_4 = block(OneiricconceptModBlocks.GEOOO_4);
	public static final DeferredItem<Item> GEOOO_7 = block(OneiricconceptModBlocks.GEOOO_7);
	public static final DeferredItem<Item> FULMO_5 = block(OneiricconceptModBlocks.FULMO_5);
	public static final DeferredItem<Item> FULMO_6 = block(OneiricconceptModBlocks.FULMO_6);
	public static final DeferredItem<Item> FULMO_8 = block(OneiricconceptModBlocks.FULMO_8);
	public static final DeferredItem<Item> FULMO_9 = block(OneiricconceptModBlocks.FULMO_9);
	public static final DeferredItem<Item> FULMO_10 = block(OneiricconceptModBlocks.FULMO_10);
	public static final DeferredItem<Item> REDMO_5 = block(OneiricconceptModBlocks.REDMO_5);
	public static final DeferredItem<Item> REDMO_6 = block(OneiricconceptModBlocks.REDMO_6);
	public static final DeferredItem<Item> REDMO_8 = block(OneiricconceptModBlocks.REDMO_8);
	public static final DeferredItem<Item> REDMO_9 = block(OneiricconceptModBlocks.REDMO_9);
	public static final DeferredItem<Item> REDMO_10 = block(OneiricconceptModBlocks.REDMO_10);
	public static final DeferredItem<Item> LIRON_5 = block(OneiricconceptModBlocks.LIRON_5);
	public static final DeferredItem<Item> LIRON_6 = block(OneiricconceptModBlocks.LIRON_6);
	public static final DeferredItem<Item> LIRON_8 = block(OneiricconceptModBlocks.LIRON_8);
	public static final DeferredItem<Item> LIRON_9 = block(OneiricconceptModBlocks.LIRON_9);
	public static final DeferredItem<Item> LIRON_10 = block(OneiricconceptModBlocks.LIRON_10);
	public static final DeferredItem<Item> ELECT_5 = block(OneiricconceptModBlocks.ELECT_5);
	public static final DeferredItem<Item> ELECT_6 = block(OneiricconceptModBlocks.ELECT_6);
	public static final DeferredItem<Item> ELECT_8 = block(OneiricconceptModBlocks.ELECT_8);
	public static final DeferredItem<Item> ELECT_9 = block(OneiricconceptModBlocks.ELECT_9);
	public static final DeferredItem<Item> ELECT_10 = block(OneiricconceptModBlocks.ELECT_10);
	public static final DeferredItem<Item> HYDRO_5 = block(OneiricconceptModBlocks.HYDRO_5);
	public static final DeferredItem<Item> HYDRO_6 = block(OneiricconceptModBlocks.HYDRO_6);
	public static final DeferredItem<Item> HYDRO_8 = block(OneiricconceptModBlocks.HYDRO_8);
	public static final DeferredItem<Item> HYDRO_9 = block(OneiricconceptModBlocks.HYDRO_9);
	public static final DeferredItem<Item> HYDRO_10 = block(OneiricconceptModBlocks.HYDRO_10);
	public static final DeferredItem<Item> CRYOO_5 = block(OneiricconceptModBlocks.CRYOO_5);
	public static final DeferredItem<Item> CRYOO_6 = block(OneiricconceptModBlocks.CRYOO_6);
	public static final DeferredItem<Item> CRYOO_8 = block(OneiricconceptModBlocks.CRYOO_8);
	public static final DeferredItem<Item> CRYOO_9 = block(OneiricconceptModBlocks.CRYOO_9);
	public static final DeferredItem<Item> CRYOO_10 = block(OneiricconceptModBlocks.CRYOO_10);
	public static final DeferredItem<Item> DENDR_5 = block(OneiricconceptModBlocks.DENDR_5);
	public static final DeferredItem<Item> DENDR_6 = block(OneiricconceptModBlocks.DENDR_6);
	public static final DeferredItem<Item> DENDR_8 = block(OneiricconceptModBlocks.DENDR_8);
	public static final DeferredItem<Item> DENDR_9 = block(OneiricconceptModBlocks.DENDR_9);
	public static final DeferredItem<Item> DENDR_10 = block(OneiricconceptModBlocks.DENDR_10);
	public static final DeferredItem<Item> ANEMO_5 = block(OneiricconceptModBlocks.ANEMO_5);
	public static final DeferredItem<Item> ANEMO_6 = block(OneiricconceptModBlocks.ANEMO_6);
	public static final DeferredItem<Item> ANEMO_8 = block(OneiricconceptModBlocks.ANEMO_8);
	public static final DeferredItem<Item> ANEMO_9 = block(OneiricconceptModBlocks.ANEMO_9);
	public static final DeferredItem<Item> ANEMO_10 = block(OneiricconceptModBlocks.ANEMO_10);
	public static final DeferredItem<Item> GEOOO_5 = block(OneiricconceptModBlocks.GEOOO_5);
	public static final DeferredItem<Item> GEOOO_6 = block(OneiricconceptModBlocks.GEOOO_6);
	public static final DeferredItem<Item> GEOOO_8 = block(OneiricconceptModBlocks.GEOOO_8);
	public static final DeferredItem<Item> GEOOO_9 = block(OneiricconceptModBlocks.GEOOO_9);
	public static final DeferredItem<Item> GEOOO_10 = block(OneiricconceptModBlocks.GEOOO_10);
	public static final DeferredItem<Item> SUPERIMPOSER_CUSTOMMADE = block(OneiricconceptModBlocks.SUPERIMPOSER_CUSTOMMADE);
	public static final DeferredItem<Item> HBOND_0 = block(OneiricconceptModBlocks.HBOND_0);
	public static final DeferredItem<Item> HBOND_1 = block(OneiricconceptModBlocks.HBOND_1);
	public static final DeferredItem<Item> HBOND_2 = block(OneiricconceptModBlocks.HBOND_2);
	public static final DeferredItem<Item> HBOND_3 = block(OneiricconceptModBlocks.HBOND_3);
	public static final DeferredItem<Item> HBOND_4 = block(OneiricconceptModBlocks.HBOND_4);
	public static final DeferredItem<Item> HBOND_5 = block(OneiricconceptModBlocks.HBOND_5);
	public static final DeferredItem<Item> HBOND_6 = block(OneiricconceptModBlocks.HBOND_6);
	public static final DeferredItem<Item> HBOND_7 = block(OneiricconceptModBlocks.HBOND_7);
	public static final DeferredItem<Item> HBOND_8 = block(OneiricconceptModBlocks.HBOND_8);
	public static final DeferredItem<Item> HBOND_9 = block(OneiricconceptModBlocks.HBOND_9);
	public static final DeferredItem<Item> HBOND_10 = block(OneiricconceptModBlocks.HBOND_10);
	public static final DeferredItem<Item> PYROSEALINGWAX = block(OneiricconceptModBlocks.PYROSEALINGWAX);
	public static final DeferredItem<Item> ELECTROSEALINGWAX = block(OneiricconceptModBlocks.ELECTROSEALINGWAX);
	public static final DeferredItem<Item> HYDROSEALINGWAX = block(OneiricconceptModBlocks.HYDROSEALINGWAX);
	public static final DeferredItem<Item> CRYOSEALINGWAX = block(OneiricconceptModBlocks.CRYOSEALINGWAX);
	public static final DeferredItem<Item> DENDROSEALINGWAX = block(OneiricconceptModBlocks.DENDROSEALINGWAX);
	public static final DeferredItem<Item> ANEMO_SEALINGWAX = block(OneiricconceptModBlocks.ANEMO_SEALINGWAX);
	public static final DeferredItem<Item> GEOSEALINGWAX = block(OneiricconceptModBlocks.GEOSEALINGWAX);
	public static final DeferredItem<Item> AMBROSIAL_ARBOR_LOG = block(OneiricconceptModBlocks.AMBROSIAL_ARBOR_LOG);
	public static final DeferredItem<Item> AMBROSIAL_ARBOR_LEAVE = block(OneiricconceptModBlocks.AMBROSIAL_ARBOR_LEAVE);
	public static final DeferredItem<Item> IGNIS_AURELIAE = REGISTRY.register("ignis_aureliae", IgnisAureliaeItem::new);
	public static final DeferredItem<Item> AURELIAE_PICKAXE = REGISTRY.register("aureliae_pickaxe", AureliaePickaxeItem::new);
	public static final DeferredItem<Item> AURELIAE_AXE = REGISTRY.register("aureliae_axe", AureliaeAxeItem::new);
	public static final DeferredItem<Item> AURELIAE_SWORD = REGISTRY.register("aureliae_sword", AureliaeSwordItem::new);
	public static final DeferredItem<Item> AURELIAE_SHOVEL = REGISTRY.register("aureliae_shovel", AureliaeShovelItem::new);
	public static final DeferredItem<Item> AURELIAE_HOE = REGISTRY.register("aureliae_hoe", AureliaeHoeItem::new);
	public static final DeferredItem<Item> MOLTEN_METAL = REGISTRY.register("molten_metal", MoltenMetalItem::new);
	public static final DeferredItem<Item> MOLTEN_METAL_BLOCK = block(OneiricconceptModBlocks.MOLTEN_METAL_BLOCK);
	public static final DeferredItem<Item> PRIMOGEMFRUITBLOCK = block(OneiricconceptModBlocks.PRIMOGEMFRUITBLOCK);
	public static final DeferredItem<Item> PRIMOGEMFRUIT = REGISTRY.register("primogemfruit", PrimogemfruitItem::new);
	public static final DeferredItem<Item> AMBROSIAL_ARBOR_SAPLING = block(OneiricconceptModBlocks.AMBROSIAL_ARBOR_SAPLING);
	public static final DeferredItem<Item> AMBROSIAL_ARBOR_PLANK = block(OneiricconceptModBlocks.AMBROSIAL_ARBOR_PLANK);
	public static final DeferredItem<Item> HILTWOOD_FROM_THE_ARBOR = REGISTRY.register("hiltwood_from_the_arbor", HiltwoodFromTheArborItem::new);
	public static final DeferredItem<Item> WAYFAREBLESSING = block(OneiricconceptModBlocks.WAYFAREBLESSING);
	public static final DeferredItem<Item> HEARTOFTHEFROZENSEA = REGISTRY.register("heartofthefrozensea", HeartofthefrozenseaItem::new);
	public static final DeferredItem<Item> HEARTOFTHESKYSEA = REGISTRY.register("heartoftheskysea", HeartoftheskyseaItem::new);
	public static final DeferredItem<Item> HEARTOFTHEWARMSEA = REGISTRY.register("heartofthewarmsea", HeartofthewarmseaItem::new);
	public static final DeferredItem<Item> HEARTOFTHEVASTSEA = REGISTRY.register("heartofthevastsea", HeartofthevastseaItem::new);
	public static final DeferredItem<Item> FLOATING_CLOUD = block(OneiricconceptModBlocks.FLOATING_CLOUD);
	public static final DeferredItem<Item> SALT = REGISTRY.register("salt", SaltItem::new);
	public static final DeferredItem<Item> MILK = REGISTRY.register("milk", MilkItem::new);
	public static final DeferredItem<Item> RED_BEAN_SOUP_FILLING_YUAN_XIAO = REGISTRY.register("red_bean_soup_filling_yuan_xiao", RedBeanSoupFillingYuanXiaoItem::new);
	public static final DeferredItem<Item> SWEET_SESAME_FILLING_YUAN_XIAO = REGISTRY.register("sweet_sesame_filling_yuan_xiao", SweetSesameFillingYuanXiaoItem::new);
	public static final DeferredItem<Item> GRILLED_OY_DUMPLING = REGISTRY.register("grilled_oy_dumpling", GrilledOyDumplingItem::new);
	public static final DeferredItem<Item> GRILLED_DUMPLING = REGISTRY.register("grilled_dumpling", GrilledDumplingItem::new);
	public static final DeferredItem<Item> SALT_DUST = REGISTRY.register("salt_dust", SaltDustItem::new);
	public static final DeferredItem<Item> HUNGER = REGISTRY.register("hunger", HungerItem::new);
	public static final DeferredItem<Item> AMBROSIAL_ARBOR_WOOD = block(OneiricconceptModBlocks.AMBROSIAL_ARBOR_WOOD);
	public static final DeferredItem<Item> AMBERGRIS_CHEESE_SLIVER = REGISTRY.register("ambergris_cheese_sliver", AmbergrisCheeseSliverItem::new);
	public static final DeferredItem<Item> DIVINE_ARROW_EMBERS = REGISTRY.register("divine_arrow_embers", DivineArrowEmbersItem::new);

	// Start of user code block custom items
	// End of user code block custom items
	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}

	@EventBusSubscriber(bus = EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class ItemsClientSideHandler {
		@SubscribeEvent
		@OnlyIn(Dist.CLIENT)
		public static void clientLoad(FMLClientSetupEvent event) {
			event.enqueueWork(() -> {
				ItemProperties.register(HEARTOFTHEVASTSEA.get(), ResourceLocation.parse("oneiricconcept:heartofthevastsea_itemmode"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) VastmodeProcedure.execute(itemStackToRender));
			});
		}
	}
}
