
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.oneiricconcept.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.client.event.RegisterColorHandlersEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;

import net.mcreator.oneiricconcept.block.YactusBlock;
import net.mcreator.oneiricconcept.block.VayudaTurquoiseOreBlock;
import net.mcreator.oneiricconcept.block.VarunadaLazuriteOreBlock;
import net.mcreator.oneiricconcept.block.VajradaAmethystOreBlock;
import net.mcreator.oneiricconcept.block.ThunderSwordBlock;
import net.mcreator.oneiricconcept.block.TheAnotherWorldWoodBlock;
import net.mcreator.oneiricconcept.block.TheAnotherWorldSaplingBlock;
import net.mcreator.oneiricconcept.block.TheAnotherWorldLogBlock;
import net.mcreator.oneiricconcept.block.TheAnotherWorldLeaveBlock;
import net.mcreator.oneiricconcept.block.TNTDispenserBlock;
import net.mcreator.oneiricconcept.block.SustenanceanchoroffBlock;
import net.mcreator.oneiricconcept.block.SustenanceanchorBlock;
import net.mcreator.oneiricconcept.block.StrippedTheAnotherWorldLogBlock;
import net.mcreator.oneiricconcept.block.ShivadaJadeOreBlock;
import net.mcreator.oneiricconcept.block.Redmo7Block;
import net.mcreator.oneiricconcept.block.Redmo4Block;
import net.mcreator.oneiricconcept.block.Redmo3Block;
import net.mcreator.oneiricconcept.block.Redmo2Block;
import net.mcreator.oneiricconcept.block.Redmo1Block;
import net.mcreator.oneiricconcept.block.RactusBlock;
import net.mcreator.oneiricconcept.block.PropagandaArmyBlockBlock;
import net.mcreator.oneiricconcept.block.PrithivaTopazOreBlock;
import net.mcreator.oneiricconcept.block.PgcPresentBlock;
import net.mcreator.oneiricconcept.block.PgcPgfBlock;
import net.mcreator.oneiricconcept.block.PgcPgeBlock;
import net.mcreator.oneiricconcept.block.PgcPgdBlock;
import net.mcreator.oneiricconcept.block.PgcPgcBlock;
import net.mcreator.oneiricconcept.block.PgcPgbBlock;
import net.mcreator.oneiricconcept.block.PgcPgaBlock;
import net.mcreator.oneiricconcept.block.PgcPgBlock;
import net.mcreator.oneiricconcept.block.Newmo9Block;
import net.mcreator.oneiricconcept.block.Newmo8Block;
import net.mcreator.oneiricconcept.block.Newmo7Block;
import net.mcreator.oneiricconcept.block.Newmo6Block;
import net.mcreator.oneiricconcept.block.Newmo5Block;
import net.mcreator.oneiricconcept.block.Newmo4Block;
import net.mcreator.oneiricconcept.block.Newmo3Block;
import net.mcreator.oneiricconcept.block.Newmo2Block;
import net.mcreator.oneiricconcept.block.Newmo1Block;
import net.mcreator.oneiricconcept.block.Newmo10Block;
import net.mcreator.oneiricconcept.block.NagadusEmeraldOreBlock;
import net.mcreator.oneiricconcept.block.MmMushroomBlock;
import net.mcreator.oneiricconcept.block.MemoriaBlock;
import net.mcreator.oneiricconcept.block.MactusBlock;
import net.mcreator.oneiricconcept.block.Liron7Block;
import net.mcreator.oneiricconcept.block.Liron4Block;
import net.mcreator.oneiricconcept.block.Liron3Block;
import net.mcreator.oneiricconcept.block.Liron2Block;
import net.mcreator.oneiricconcept.block.Liron1Block;
import net.mcreator.oneiricconcept.block.Hydro7Block;
import net.mcreator.oneiricconcept.block.Hydro4Block;
import net.mcreator.oneiricconcept.block.Hydro3Block;
import net.mcreator.oneiricconcept.block.Hydro2Block;
import net.mcreator.oneiricconcept.block.Hydro1Block;
import net.mcreator.oneiricconcept.block.Geooo7Block;
import net.mcreator.oneiricconcept.block.Geooo4Block;
import net.mcreator.oneiricconcept.block.Geooo3Block;
import net.mcreator.oneiricconcept.block.Geooo2Block;
import net.mcreator.oneiricconcept.block.Geooo1Block;
import net.mcreator.oneiricconcept.block.GeomarrowRadiatorBlock;
import net.mcreator.oneiricconcept.block.GactusBlock;
import net.mcreator.oneiricconcept.block.Fulmo7Block;
import net.mcreator.oneiricconcept.block.Fulmo4Block;
import net.mcreator.oneiricconcept.block.Fulmo3Block;
import net.mcreator.oneiricconcept.block.Fulmo2Block;
import net.mcreator.oneiricconcept.block.Fulmo1Block;
import net.mcreator.oneiricconcept.block.ElementsCrystalOreBlock;
import net.mcreator.oneiricconcept.block.Elect7Block;
import net.mcreator.oneiricconcept.block.Elect4Block;
import net.mcreator.oneiricconcept.block.Elect3Block;
import net.mcreator.oneiricconcept.block.Elect2Block;
import net.mcreator.oneiricconcept.block.Elect1Block;
import net.mcreator.oneiricconcept.block.Dendr7Block;
import net.mcreator.oneiricconcept.block.Dendr4Block;
import net.mcreator.oneiricconcept.block.Dendr3Block;
import net.mcreator.oneiricconcept.block.Dendr2Block;
import net.mcreator.oneiricconcept.block.Dendr1Block;
import net.mcreator.oneiricconcept.block.Cryoo7Block;
import net.mcreator.oneiricconcept.block.Cryoo4Block;
import net.mcreator.oneiricconcept.block.Cryoo3Block;
import net.mcreator.oneiricconcept.block.Cryoo2Block;
import net.mcreator.oneiricconcept.block.Cryoo1Block;
import net.mcreator.oneiricconcept.block.CloudBlock;
import net.mcreator.oneiricconcept.block.CameraBlock;
import net.mcreator.oneiricconcept.block.CCactusBlock;
import net.mcreator.oneiricconcept.block.BoomBlossomsPyroBlock;
import net.mcreator.oneiricconcept.block.BigStoneBlock;
import net.mcreator.oneiricconcept.block.BigRockBlock;
import net.mcreator.oneiricconcept.block.BananaMushroomBockBlock;
import net.mcreator.oneiricconcept.block.BananaMushroomBlock;
import net.mcreator.oneiricconcept.block.BactusBlock;
import net.mcreator.oneiricconcept.block.Anemo7Block;
import net.mcreator.oneiricconcept.block.Anemo4Block;
import net.mcreator.oneiricconcept.block.Anemo3Block;
import net.mcreator.oneiricconcept.block.Anemo2Block;
import net.mcreator.oneiricconcept.block.Anemo1Block;
import net.mcreator.oneiricconcept.block.AgnidusAgateOreBlock;
import net.mcreator.oneiricconcept.block.Agnid9Block;
import net.mcreator.oneiricconcept.block.Agnid8Block;
import net.mcreator.oneiricconcept.block.Agnid7Block;
import net.mcreator.oneiricconcept.block.Agnid6Block;
import net.mcreator.oneiricconcept.block.Agnid5Block;
import net.mcreator.oneiricconcept.block.Agnid4Block;
import net.mcreator.oneiricconcept.block.Agnid3Block;
import net.mcreator.oneiricconcept.block.Agnid2Block;
import net.mcreator.oneiricconcept.block.Agnid1Block;
import net.mcreator.oneiricconcept.block.Agnid10Block;
import net.mcreator.oneiricconcept.OneiricconceptMod;

public class OneiricconceptModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(OneiricconceptMod.MODID);
	public static final DeferredBlock<Block> GEOMARROW_RADIATOR = REGISTRY.register("geomarrow_radiator", GeomarrowRadiatorBlock::new);
	public static final DeferredBlock<Block> BOOM_BLOSSOMS_PYRO = REGISTRY.register("boom_blossoms_pyro", BoomBlossomsPyroBlock::new);
	public static final DeferredBlock<Block> BANANA_MUSHROOM = REGISTRY.register("banana_mushroom", BananaMushroomBlock::new);
	public static final DeferredBlock<Block> BANANA_MUSHROOM_BOCK = REGISTRY.register("banana_mushroom_bock", BananaMushroomBockBlock::new);
	public static final DeferredBlock<Block> ELEMENTS_CRYSTAL_ORE = REGISTRY.register("elements_crystal_ore", ElementsCrystalOreBlock::new);
	public static final DeferredBlock<Block> NAGADUS_EMERALD_ORE = REGISTRY.register("nagadus_emerald_ore", NagadusEmeraldOreBlock::new);
	public static final DeferredBlock<Block> SHIVADA_JADE_ORE = REGISTRY.register("shivada_jade_ore", ShivadaJadeOreBlock::new);
	public static final DeferredBlock<Block> VAJRADA_AMETHYST_ORE = REGISTRY.register("vajrada_amethyst_ore", VajradaAmethystOreBlock::new);
	public static final DeferredBlock<Block> VARUNADA_LAZURITE_ORE = REGISTRY.register("varunada_lazurite_ore", VarunadaLazuriteOreBlock::new);
	public static final DeferredBlock<Block> CLOUD = REGISTRY.register("cloud", CloudBlock::new);
	public static final DeferredBlock<Block> PRITHIVA_TOPAZ_ORE = REGISTRY.register("prithiva_topaz_ore", PrithivaTopazOreBlock::new);
	public static final DeferredBlock<Block> VAYUDA_TURQUOISE_ORE = REGISTRY.register("vayuda_turquoise_ore", VayudaTurquoiseOreBlock::new);
	public static final DeferredBlock<Block> AGNIDUS_AGATE_ORE = REGISTRY.register("agnidus_agate_ore", AgnidusAgateOreBlock::new);
	public static final DeferredBlock<Block> MEMORIA = REGISTRY.register("memoria", MemoriaBlock::new);
	public static final DeferredBlock<Block> BIG_STONE = REGISTRY.register("big_stone", BigStoneBlock::new);
	public static final DeferredBlock<Block> BIG_ROCK = REGISTRY.register("big_rock", BigRockBlock::new);
	public static final DeferredBlock<Block> THE_ANOTHER_WORLD_LOG = REGISTRY.register("the_another_world_log", TheAnotherWorldLogBlock::new);
	public static final DeferredBlock<Block> STRIPPED_THE_ANOTHER_WORLD_LOG = REGISTRY.register("stripped_the_another_world_log", StrippedTheAnotherWorldLogBlock::new);
	public static final DeferredBlock<Block> THE_ANOTHER_WORLD_SAPLING = REGISTRY.register("the_another_world_sapling", TheAnotherWorldSaplingBlock::new);
	public static final DeferredBlock<Block> THE_ANOTHER_WORLD_WOOD = REGISTRY.register("the_another_world_wood", TheAnotherWorldWoodBlock::new);
	public static final DeferredBlock<Block> MM_MUSHROOM = REGISTRY.register("mm_mushroom", MmMushroomBlock::new);
	public static final DeferredBlock<Block> BACTUS = REGISTRY.register("bactus", BactusBlock::new);
	public static final DeferredBlock<Block> C_CACTUS = REGISTRY.register("c_cactus", CCactusBlock::new);
	public static final DeferredBlock<Block> GACTUS = REGISTRY.register("gactus", GactusBlock::new);
	public static final DeferredBlock<Block> MACTUS = REGISTRY.register("mactus", MactusBlock::new);
	public static final DeferredBlock<Block> RACTUS = REGISTRY.register("ractus", RactusBlock::new);
	public static final DeferredBlock<Block> YACTUS = REGISTRY.register("yactus", YactusBlock::new);
	public static final DeferredBlock<Block> THE_ANOTHER_WORLD_LEAVE = REGISTRY.register("the_another_world_leave", TheAnotherWorldLeaveBlock::new);
	public static final DeferredBlock<Block> TNT_DISPENSER = REGISTRY.register("tnt_dispenser", TNTDispenserBlock::new);
	public static final DeferredBlock<Block> PROPAGANDA_ARMY_BLOCK = REGISTRY.register("propaganda_army_block", PropagandaArmyBlockBlock::new);
	public static final DeferredBlock<Block> THUNDER_SWORD = REGISTRY.register("thunder_sword", ThunderSwordBlock::new);
	public static final DeferredBlock<Block> PGC_PRESENT = REGISTRY.register("pgc_present", PgcPresentBlock::new);
	public static final DeferredBlock<Block> PGC_PG1 = REGISTRY.register("pgc_pg1", PgcPgBlock::new);
	public static final DeferredBlock<Block> PGC_PG2 = REGISTRY.register("pgc_pg2", PgcPgaBlock::new);
	public static final DeferredBlock<Block> PGC_PG3 = REGISTRY.register("pgc_pg3", PgcPgbBlock::new);
	public static final DeferredBlock<Block> PGC_PG4 = REGISTRY.register("pgc_pg4", PgcPgcBlock::new);
	public static final DeferredBlock<Block> PGC_PG5 = REGISTRY.register("pgc_pg5", PgcPgdBlock::new);
	public static final DeferredBlock<Block> PGC_PG6 = REGISTRY.register("pgc_pg6", PgcPgeBlock::new);
	public static final DeferredBlock<Block> PGC_PG7 = REGISTRY.register("pgc_pg7", PgcPgfBlock::new);
	public static final DeferredBlock<Block> AGNID_1 = REGISTRY.register("agnid_1", Agnid1Block::new);
	public static final DeferredBlock<Block> AGNID_2 = REGISTRY.register("agnid_2", Agnid2Block::new);
	public static final DeferredBlock<Block> AGNID_3 = REGISTRY.register("agnid_3", Agnid3Block::new);
	public static final DeferredBlock<Block> AGNID_4 = REGISTRY.register("agnid_4", Agnid4Block::new);
	public static final DeferredBlock<Block> AGNID_5 = REGISTRY.register("agnid_5", Agnid5Block::new);
	public static final DeferredBlock<Block> AGNID_6 = REGISTRY.register("agnid_6", Agnid6Block::new);
	public static final DeferredBlock<Block> AGNID_7 = REGISTRY.register("agnid_7", Agnid7Block::new);
	public static final DeferredBlock<Block> AGNID_8 = REGISTRY.register("agnid_8", Agnid8Block::new);
	public static final DeferredBlock<Block> AGNID_9 = REGISTRY.register("agnid_9", Agnid9Block::new);
	public static final DeferredBlock<Block> AGNID_10 = REGISTRY.register("agnid_10", Agnid10Block::new);
	public static final DeferredBlock<Block> CAMERA = REGISTRY.register("camera", CameraBlock::new);
	public static final DeferredBlock<Block> SUSTENANCEANCHOROFF = REGISTRY.register("sustenanceanchoroff", SustenanceanchoroffBlock::new);
	public static final DeferredBlock<Block> SUSTENANCEANCHOR = REGISTRY.register("sustenanceanchor", SustenanceanchorBlock::new);
	public static final DeferredBlock<Block> NEWMO_1 = REGISTRY.register("newmo_1", Newmo1Block::new);
	public static final DeferredBlock<Block> NEWMO_2 = REGISTRY.register("newmo_2", Newmo2Block::new);
	public static final DeferredBlock<Block> NEWMO_3 = REGISTRY.register("newmo_3", Newmo3Block::new);
	public static final DeferredBlock<Block> NEWMO_4 = REGISTRY.register("newmo_4", Newmo4Block::new);
	public static final DeferredBlock<Block> NEWMO_7 = REGISTRY.register("newmo_7", Newmo7Block::new);
	public static final DeferredBlock<Block> NEWMO_5 = REGISTRY.register("newmo_5", Newmo5Block::new);
	public static final DeferredBlock<Block> NEWMO_6 = REGISTRY.register("newmo_6", Newmo6Block::new);
	public static final DeferredBlock<Block> NEWMO_8 = REGISTRY.register("newmo_8", Newmo8Block::new);
	public static final DeferredBlock<Block> NEWMO_9 = REGISTRY.register("newmo_9", Newmo9Block::new);
	public static final DeferredBlock<Block> NEWMO_10 = REGISTRY.register("newmo_10", Newmo10Block::new);
	public static final DeferredBlock<Block> REDMO_1 = REGISTRY.register("redmo_1", Redmo1Block::new);
	public static final DeferredBlock<Block> REDMO_2 = REGISTRY.register("redmo_2", Redmo2Block::new);
	public static final DeferredBlock<Block> REDMO_3 = REGISTRY.register("redmo_3", Redmo3Block::new);
	public static final DeferredBlock<Block> REDMO_4 = REGISTRY.register("redmo_4", Redmo4Block::new);
	public static final DeferredBlock<Block> REDMO_7 = REGISTRY.register("redmo_7", Redmo7Block::new);
	public static final DeferredBlock<Block> FULMO_1 = REGISTRY.register("fulmo_1", Fulmo1Block::new);
	public static final DeferredBlock<Block> FULMO_2 = REGISTRY.register("fulmo_2", Fulmo2Block::new);
	public static final DeferredBlock<Block> FULMO_3 = REGISTRY.register("fulmo_3", Fulmo3Block::new);
	public static final DeferredBlock<Block> FULMO_4 = REGISTRY.register("fulmo_4", Fulmo4Block::new);
	public static final DeferredBlock<Block> FULMO_7 = REGISTRY.register("fulmo_7", Fulmo7Block::new);
	public static final DeferredBlock<Block> LIRON_1 = REGISTRY.register("liron_1", Liron1Block::new);
	public static final DeferredBlock<Block> LIRON_2 = REGISTRY.register("liron_2", Liron2Block::new);
	public static final DeferredBlock<Block> LIRON_3 = REGISTRY.register("liron_3", Liron3Block::new);
	public static final DeferredBlock<Block> LIRON_4 = REGISTRY.register("liron_4", Liron4Block::new);
	public static final DeferredBlock<Block> LIRON_7 = REGISTRY.register("liron_7", Liron7Block::new);
	public static final DeferredBlock<Block> ELECT_1 = REGISTRY.register("elect_1", Elect1Block::new);
	public static final DeferredBlock<Block> ELECT_2 = REGISTRY.register("elect_2", Elect2Block::new);
	public static final DeferredBlock<Block> ELECT_3 = REGISTRY.register("elect_3", Elect3Block::new);
	public static final DeferredBlock<Block> ELECT_4 = REGISTRY.register("elect_4", Elect4Block::new);
	public static final DeferredBlock<Block> ELECT_7 = REGISTRY.register("elect_7", Elect7Block::new);
	public static final DeferredBlock<Block> HYDRO_1 = REGISTRY.register("hydro_1", Hydro1Block::new);
	public static final DeferredBlock<Block> HYDRO_2 = REGISTRY.register("hydro_2", Hydro2Block::new);
	public static final DeferredBlock<Block> HYDRO_3 = REGISTRY.register("hydro_3", Hydro3Block::new);
	public static final DeferredBlock<Block> HYDRO_4 = REGISTRY.register("hydro_4", Hydro4Block::new);
	public static final DeferredBlock<Block> HYDRO_7 = REGISTRY.register("hydro_7", Hydro7Block::new);
	public static final DeferredBlock<Block> CRYOO_1 = REGISTRY.register("cryoo_1", Cryoo1Block::new);
	public static final DeferredBlock<Block> CRYOO_2 = REGISTRY.register("cryoo_2", Cryoo2Block::new);
	public static final DeferredBlock<Block> CRYOO_3 = REGISTRY.register("cryoo_3", Cryoo3Block::new);
	public static final DeferredBlock<Block> CRYOO_4 = REGISTRY.register("cryoo_4", Cryoo4Block::new);
	public static final DeferredBlock<Block> CRYOO_7 = REGISTRY.register("cryoo_7", Cryoo7Block::new);
	public static final DeferredBlock<Block> DENDR_1 = REGISTRY.register("dendr_1", Dendr1Block::new);
	public static final DeferredBlock<Block> DENDR_2 = REGISTRY.register("dendr_2", Dendr2Block::new);
	public static final DeferredBlock<Block> DENDR_3 = REGISTRY.register("dendr_3", Dendr3Block::new);
	public static final DeferredBlock<Block> DENDR_4 = REGISTRY.register("dendr_4", Dendr4Block::new);
	public static final DeferredBlock<Block> DENDR_7 = REGISTRY.register("dendr_7", Dendr7Block::new);
	public static final DeferredBlock<Block> ANEMO_1 = REGISTRY.register("anemo_1", Anemo1Block::new);
	public static final DeferredBlock<Block> ANEMO_2 = REGISTRY.register("anemo_2", Anemo2Block::new);
	public static final DeferredBlock<Block> ANEMO_3 = REGISTRY.register("anemo_3", Anemo3Block::new);
	public static final DeferredBlock<Block> ANEMO_4 = REGISTRY.register("anemo_4", Anemo4Block::new);
	public static final DeferredBlock<Block> ANEMO_7 = REGISTRY.register("anemo_7", Anemo7Block::new);
	public static final DeferredBlock<Block> GEOOO_1 = REGISTRY.register("geooo_1", Geooo1Block::new);
	public static final DeferredBlock<Block> GEOOO_2 = REGISTRY.register("geooo_2", Geooo2Block::new);
	public static final DeferredBlock<Block> GEOOO_3 = REGISTRY.register("geooo_3", Geooo3Block::new);
	public static final DeferredBlock<Block> GEOOO_4 = REGISTRY.register("geooo_4", Geooo4Block::new);
	public static final DeferredBlock<Block> GEOOO_7 = REGISTRY.register("geooo_7", Geooo7Block::new);

	// Start of user code block custom blocks
	// End of user code block custom blocks
	@EventBusSubscriber(bus = EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class BlocksClientSideHandler {
		@SubscribeEvent
		public static void blockColorLoad(RegisterColorHandlersEvent.Block event) {
			Hydro1Block.blockColorLoad(event);
			Dendr1Block.blockColorLoad(event);
			Anemo1Block.blockColorLoad(event);
		}
	}
}
